### PR TITLE
DrinkWave3

### PR DESCRIPTION
**Pull request by SleepyScarecrow**
# Description

Adding in 24 more community-suggested drinks.

---

# TODO

- [x] Added more Drinks

---

# Changelog

:cl: Tilkku
- add: 24 More Drinks

### CODE REVIEW

**Comment by ShatteredSwords** [comment]
Test fails are legit, issues are as follows:
- DeadMansDrought needs reagent-desc-deadmansdrought Localization
- Dirty Wastelander needs reagent-physical-desc-dirty Localization 
- BethanysSluttyCumLust needs reagent-desc-BethanysSluttyCumLust

**Comment by ShatteredSwords** [comment]
Ah lools like you handled em

**Comment by ShatteredSwords** [comment]
You seem to know what you are doing, I'll leave you to it o7

**Comment by SleepyScarecrow** [comment]
ignore that commit name i fucked up cherry picking lol

**Comment by ShatteredSwords** [comment]
That error looks valid but I honestly couldn't tell you what's wrong with it

**Comment by SleepyScarecrow** [comment]
I can't figure it out either
I've had this happen a lot, with the random build error that is actually fine but idk

**Comment by SleepyScarecrow** [comment]
idk if the build fail is valid or not

**Comment by SleepyScarecrow** [comment]
like I've seen this before but it doesn't actually seem to fuck up anything?

**Comment by ShatteredSwords** [comment]
There is a possibility that one of these newly added drinks overwrites another recipe. Worth taking a look at.

**Comment by ShatteredSwords** [comment]
There is also a possibility that one of the vanilla recipes overwrites one of these drinks before they can be made.

**Comment by SleepyScarecrow** [comment]
i think the issue was the prisonwine recipe, it directly overwrote the grapesoda recipe

**Comment by SleepyScarecrow** [comment]
works now :3

**Review by Memeji — APPROVED** [review]

**Review by FoxxoTrystan — APPROVED** [review]

**Pull request merged**
