### PR TITLE
Muffled Gas Masks

### PR DESCRIPTION
**Pull request by sarcoph**
# Description

This PR adds "muffled" variants to three different gas mask types; the regular gas mask, explorer gas masks, and security gas masks. These muffled gas masks combine the best of both muzzles and gas masks, allowing you to breathe from an internals tank but not allowing you to speak like a normal person.

**Why?** It's practical. It has sex appeal. It's giving me character ideas. We are one step closer to gear fetish roleplay. It's fucking genius

As another note, this was originally meant to be for a larger PR that involved adding a lot more BDSM/bondage gear (more muzzle and handcuff variants), but this specific feature involved minorly refactoring upstream YAML in a kind of questionable way, so I am PRing this separately for the sake of reviews.

## Technical details

The gas masks and muzzle all get a new tag that's like, "[part of the item ID]Ingredient", and that is used in the crafting recipe because recipes are tag-based and not prototype-based. However, I did not want the final result (the muffled gas masks themselves) to have the ingredient tags, so I had to do some nasty-ass YAML refactoring to manipulate the tags in this way. 

The fact tags do not allow for inheritance (i.e. inheriting the tag list from parents and being able to tack new entries on) kind of encourages repetitive YAML behavior, unfortunately, but on the other hand it CAN be taken advantage of like I did in this case to remove the ingredient tags in the final result.

As for why I did this weird multiple inheritance take instead of just making a new prototype inheriting from MaskBase: For consistency in case any changes to the regular gas masks are made (besides, uh, their tags)

---

# TODO

- [x] Add muffled gas masks.
- [x] Add crafting recipe for muffled gas masks.
- [x] Look into where else they could be added besides crafting menu (e.g. loadouts).

---

<details><summary><h1>Media</h1></summary>
<p>

A passenger wearing the muffled gas mask and attempting to speak; it only comes out as "Mmfph!"

Crafting menu showing that you can craft a muffled gas mask, muffled explorer gas mask, or muffled security gas mask. The regular one just takes a gas mask and a muzzle.

</p>
</details>

---

# Changelog
:cl:
- add: New "muffled" variants for the regular, explorer, and security gas masks, for people who love breathing almost as much as they love speaking unintelligibly. They can be obtained via the crafting tab, or the regular one can be found in loadouts.

### CODE REVIEW

**Comment by Memeji** [comment]
I will review this PR in detail.

**Comment by ShatteredSwords** [comment]
I will playtest this when I get home

**Review by ShatteredSwords — CHANGES_REQUESTED** [review]
Can confirm that it works after playtesting. There may be a few merge conflict errors that pop up from this. 

You should always comment out lines instead of remove them if you're messing with things from upstream.

**Comment by sarcoph** [comment]
> You should always comment out lines instead of remove them if you're messing with things from upstream.

I thought I did this but apparently not. Thanks for reminding me

**Comment by FoxxoTrystan** [comment]
Is this PR planned to be worked on?

**Comment by sarcoph** [comment]
> Is this PR planned to be worked on?

Currently I am unable to work due to real life circumstances, but I should be back in action in about two weeks. I might try to find time this week to squeeze in a merge conflict resolution, however. I apologize for the inconvenience.

**Comment by sarcoph** [comment]
Merge conflict resolved, ready for review

**Review by Fansana — APPROVED** [review]

**Comment by Fansana** [comment]
okay, there is an issue with this, by changing the prototype Id you will make every map that uses this item unloadable.

**Comment by ShatteredSwords** [comment]
> okay, there is an issue with this, by changing the prototype Id you will make every map that uses this item unloadable.

The way to fix this would be using migrations or just changing the ID back.

**Review by FoxxoTrystan — CHANGES_REQUESTED** [review]
Use Migration or revert the id changes.

**Pull request merged**
