### PR TITLE
Shadowkin

### PR DESCRIPTION
**Pull request by FoxxoTrystan**
# Description

Port PR: https://github.com/Simple-Station/Einstein-Engines/pull/960
This is an early merge and only admins will have access to the specie for the moment, please report all bugs found to @FoxxoTrystan .

Another PR will be made when Shadowkin is released for all players.

---

# Changelog

:cl:
- add: Artificial Bluespace Crystals!

### CODE REVIEW

**Review by Fansana — APPROVED** [review]

**Review by Memeji — APPROVED** [review]

**Comment by Fansana** [comment]
Please fix the tests

**Comment by FoxxoTrystan** [comment]
That why i put do not merge, fixing it.

**Comment by FoxxoTrystan** [comment]
Will merges when all tests passes.

**Comment by FoxxoTrystan** [comment]
Hmm when i mess 1 line in a merge conflict

**Comment by FoxxoTrystan** [comment]
All test passes

**Pull request merged**
