### PR TITLE
Upstream Merge 2024-09-08

### PR DESCRIPTION
**Pull request by Mnemotechnician**
# Description
Routine upstream merge. No immediate errors found during testing.

# Changelog
:cl:
- add: Upstream merge. See the einstein-engines tab for more details. Most notably, jukeboxes are now a thing!

### CODE REVIEW

**Review by Memeji — APPROVED** [review]

**Comment by cynical24** [comment]
heehee jukebox heehee

**Comment by FoxxoTrystan** [comment]
For the changelog, please keep the floof version as the floof version will update the changlog on server update and not on merge.

Or modify the workflow to execute at the same time.

**Comment by Mnemotechnician** [comment]
> For the changelog, please keep the floof version as the floof version will update the changlog on server update and not on merge.
So you want to revert the newlogs completely?

**Comment by Mnemotechnician** [comment]
Reverted the changes to the workflow except the addition of headings and some other thing.

Please, for the love of god, do a **squash** merge if this gets merged.

**Comment by cynical24** [comment]
hnhngnffnnghf... jukbeox.. ngnfgnh

**Comment by ShatteredSwords** [comment]
> hnhngnffnnghf... jukbeox.. ngnfgnh

Excuse me this is a Wendy's

**Comment by Mnemotechnician** [comment]
Now includes changes up to 2024-09-08

**Comment by Mnemotechnician** [comment]
Now featuring loadouts v3. I had to edit and split the massive 1000-line departamental loadouts file because it had become unmaintanable. But it works now:

<details>

image

image


</details>

**Pull request merged**
