### PR TITLE
Partial Merge Up to 2024-11-17

### PR DESCRIPTION
**Pull request by Mnemotechnician**
# Description
This merges a number of upstream changes up to (but not including) the surgery update. This brings a number of important changes, such as:
- [Psionic familliar nerf](https://github.com/simple-station/einstein-engines/pull/1184)
- [Language names in chat](https://github.com/simple-station/einstein-engines/pull/1165)
- [Trait refactor (floof traits had to be updated to incorporate it, all future PRs will depend on it)](https://github.com/simple-station/einstein-engines/pull/1182)
- [Bloodstains & footprints system](https://github.com/simple-station/einstein-engines/pull/1190)
- [The hotfix followup to trait rework](https://github.com/simple-station/einstein-engines/pull/1195)
- [Butlertron hitbox fix](https://github.com/simple-station/einstein-engines/pull/1192)
- [The return on spray paint](https://github.com/simple-station/einstein-engines/pull/1222)

Minor changes:
- [Carp rifts and other beacons use readable locations](https://github.com/simple-station/einstein-engines/pull/1196)
- [Shuttle calling fixes](https://github.com/simple-station/einstein-engines/pull/1199)
- ["cool punpun" (minor change, pun pun preserves items across shifts)](https://github.com/simple-station/einstein-engines/pull/1157)
- [Some BUI fix we may have incorporated already on floof](https://github.com/simple-station/einstein-engines/pull/1191)
- [Return of some old lobby music](https://github.com/simple-station/einstein-engines/pull/1204)
- [Minor code style changes](https://github.com/simple-station/einstein-engines/pull/1226)
- [Bounties localization fixes](https://github.com/simple-station/einstein-engines/pull/1219)
- [Prevention of listening posts from spawning on planets](https://github.com/simple-station/einstein-engines/pull/1188)

Mapping changes:
- [Radstation and gax fixes](https://github.com/simple-station/einstein-engines/pull/1178)
- [The replacement of hive's singularity with a supermatter](https://github.com/simple-station/einstein-engines/pull/1201)

Changes already merged into floof (ported upstream or otherwise):
- Health analyzer ui changes
- Swapped hands fix
- Silver crate naming fixes
- Auto voting system
- Language fixes
- Cold resistance on penguins

In addition, the following changes were performed:
- Nuked the female displacement repetition on all species, favoring entity parenting instead. Displacements still work (and still break jumpsuit sprites), but are no longer hardcoded.
- Added rodentia to the list of species excluded from the lightweight trait - a long awaited fix that I wasn't aware was necessary.
- Fixed disposal trunk ejection (thanks sleepyaril I gues)

---

# TODO
- [X] Ensure the game compiles & launches
- [ ] Test everything
- [x] Test the health analyzer ui
- [X] Make sure female displacements still work correctly
- [x] Make sure all floof-specific traits are still functional
- [x] FootSteps should contain DNA
- [x] FootSteps should not be created on full puddles of liquid
---

<details><summary><h1>Media</h1></summary>
<p>

Basic stuff works:

image

</p>
</details>

---

# Changelog

:cl:
- add: Merged upstream changes up to the 17th of November. See the Einstein-Engines changelog tab for more details.

### CODE REVIEW

**Comment by Mnemotechnician** [comment]
Even though the tests pass, I kindly ask not to merge this until we can make sure this merge doesn't create a ton of new issues.

**Comment by FoxxoTrystan** [comment]
resomi is a reskin of the human and should weight should be the same

**Comment by Mnemotechnician** [comment]
> resomi is a reskin of the human and should weight should be the same

Is it? Its fixture radius is 0.35m, default is I think 0.45

**Comment by FoxxoTrystan** [comment]
> > resomi is a reskin of the human and should weight should be the same
> 
> Is it? Its fixture radius is 0.35m, default is I think 0.45

if its inst, fix it please.

**Comment by Fansana** [comment]
shuttle calling fixes are already in floof I think

**Comment by sleepyyapril** [comment]
You may want to partial merge my disposal fix. It fixes your issue of when _current_ direction is Direction.Invalid. [But it's basically just this.](https://github.com/Simple-Station/Einstein-Engines/blob/a668d35b8a8a5e845fc0e58d7e8199ab8ba79cc5/Content.Server/Disposal/Unit/EntitySystems/DisposableSystem.cs#L140C21-L147C22)

**Comment by Mnemotechnician** [comment]
I just found arachne lack their own male/female jumpsuit displacements and as such look extremely cursed. But other than that, everything that used to work still works.

**Review by Fansana — APPROVED** [review]

**Comment by FoxxoTrystan** [comment]
Before this is merged i will mostly edit the maps and give them the needed floof changes included in those.

**Comment by sleepyyapril** [comment]
EE got my full slider fix which was fully tested. Revert 8c096b7 and use the full PR.

**Pull request merged**
