### PR TITLE
Silly Slimes

### PR DESCRIPTION
**Pull request by fenndragon**
# Description

This adds several new types of reagent slimes to the spawn tables 

---

# Changelog

:cl:
- add: the following Reagent slime entities 
        - ReagentSlimeCum
        - ReagentSlimePomelustine
        - ReagentSlimePhilterex
        - ReagentSlimeLibidozenithizine
        - ReagentSlimeIchor
        - ReagentSlimeBleach
        - ReagentSlimeSoap
        - ReagentSlimeSpacelube
        - ReagentSlimeBuzzachloricbees
        - ReagentSlimeWehjuice
        - ReagentCognizine
        - ReagentSlimeOpporozidone
        - ReagentSlimeNecrosol
        - ReagentSlimeSpaceDrugs
        - ReagentSlimeSoulbreakerToxin
        - ReagentSlimeUnstableMutagen
        - ReagentSlimeMindbreakerToxin
        - ReagentSlimeRomerol
        - ReagentSlimeLead
        - ReagentSlimechlorinetriflouride
        - ReagentSlimePotassium
        - ReagentSlimeAmbuzolPlus

### CODE REVIEW

**Review by Memeji — CHANGES_REQUESTED** [review]
Remove: 
- Romerol Slime
- Soulbreaker Slime
- Mindbreaker Slime
- AmbuzolPlus Slime

**Comment by fenndragon** [comment]
totally fair

**Comment by fenndragon** [comment]
> Remove:
> 
> * Romerol Slime
> * Soulbreaker Slime
> * Mindbreaker Slime
> * AmbuzolPlus Slime

alright this should be done now~ hopefully I can figure out why I keep having my pull and push requests throwing errors with YAML

**Comment by ShatteredSwords** [comment]
> > Remove:
> > 
> > * Romerol Slime
> > * Soulbreaker Slime
> > * Mindbreaker Slime
> > * AmbuzolPlus Slime
> 
> alright this should be done now~ hopefully I can figure out why I keep having my pull and push requests throwing errors with YAML

Looks like some of the reagents within the slimes have improper names. I can take a look when I get on

**Comment by fenndragon** [comment]
w

> > > Remove:
> > > 
> > > * Romerol Slime
> > > * Soulbreaker Slime
> > > * Mindbreaker Slime
> > > * AmbuzolPlus Slime
> > 
> > 
> > alright this should be done now~ hopefully I can figure out why I keep having my pull and push requests throwing errors with YAML
> 
> Looks like some of the reagents within the slimes have improper names. I can take a look when I get on

I think I THINK I fixed it. there were a few Reagent names that were wrong.

**Comment by fenndragon** [comment]
OK now NOW they should be right

**Comment by ShatteredSwords** [comment]
Pretty sure that's a false fail, would need to rerun the test again

**Comment by fenndragon** [comment]
fuck my life what's wrong now

**Comment by ShatteredSwords** [comment]
> fuck my life what's wrong now

Nothing, Build and Test Debug just had a stroke is all

**Review by Memeji — APPROVED** [review]

**Review by FoxxoTrystan — APPROVED** [review]

**Comment by FoxxoTrystan** [comment]
holy fuck why did i aprove and merged this?
The changlog is **HORIBLE!**

**Comment by ShatteredSwords** [comment]
> holy fuck why did i aprove and merged this? The changlog is **HORIBLE!**

I wish to see this CL on the CL list >:3c

**Comment by ShatteredSwords** [comment]
Actually it doesn't list the rest of the CL, just the first part

**Comment by fenndragon** [comment]
Apologies, should I not be listing all changes made?

**Pull request merged**
