### PR TITLE
Friend Shaped

### PR DESCRIPTION
**Pull request by fenndragon**
# Description

did some minor tweaks to the sprites for Friendshaped/rounis, added friend as an actual entity that can be spawned, modified Centcomm's map slightly to add Xeno enclosures, added a crit state to most of the different Xeno types, and fixed the unrevivable bug. 
---

# Changelog

:cl:
- add: Added Friend Shaped entity
- add: Added a crit state to most Xenos including: Friend, Rouny, Praetorian, Drone, and Ravager.  
- tweak: Tweaked the layout of Centcomm to add Xeno enclosures for their Xeno domestication program
- fix: fixed Friend being unrevivable

### CODE REVIEW

**Comment by ShatteredSwords** [comment]
It's an easy thing to forget or not do when you don't use github a lot but please make a separate branch for changes aaaa

**Comment by fenndragon** [comment]
sorry, I- am not sure what you mean, I have my own fork that I use for- oh so the modifications don't show up here?

**Comment by ShatteredSwords** [comment]
> sorry, I- am not sure what you mean, I have my own fork that I use for- oh so the modifications don't show up here?

They do show up but rule 1 of github is never ever make commits to the master branch

**Comment by fenndragon** [comment]
oh, I didn't realize I was- I thought a fork would mean it wasn't the master branch

**Pull request closed without merging**
