### PR TITLE
Increase Character Slots

### PR DESCRIPTION
**Pull request by Memeji**
# Description

Simple PR to increase the number of character slots from 10 to 50.

---

# Changelog

:cl:
- tweak: Increased Number of Character Slots to 50.

### CODE REVIEW

**Review by FoxxoTrystan — APPROVED** [review]
I would have Prefer 20 to 30.

**Comment by flyingkarii** [comment]
At the end of the day, a character slot limit doesn't change much. It simply lets people who like having different characters do so at their whims.

**Comment by Memeji** [comment]
> I would have Prefer 20 to 30.

I was told to set it to 50 since it won't be much of a problem.

**Comment by Fansana** [comment]
Changed like those don't need a PR, they an be done with a config edit.

**Pull request closed without merging**
