### PR TITLE
Character Consent Menu

### PR DESCRIPTION
**Pull request by Memeji**
# Description

WIP of a per-character consent menu.

---

# TODO

- [x] Fix Migration issues
- [x] Add Consent menu text instead of flavor text placeholders.
- [ ] Replace original consent settings
- [ ] Add consent toggles

---

# Changelog

:cl:
- add: Per-character consent menu

### CODE REVIEW

**Comment by FoxxoTrystan** [comment]
Il review this PR when im home as you doing database fiddling

**Comment by Memeji** [comment]
Your Database, it is fiddled

**Review by FoxxoTrystan — CHANGES_REQUESTED** [review]
Multiple issues has been found when testing this.

> In character menu, Consent is replacing jobs tab.
> Consent appear 2 times in the examinable menu, also unable to edit it from there.

I havent not seen or tested this but what about Consent Settings?

And this cannot be merged until the previous consent system is removed to avoid a fuckup conflict.

**Comment by FoxxoTrystan** [comment]
conset Settings.

There some already in the previous consent menu but consent settings are Yes/No toggle for this character that we can read, example.

Vore Consent (if off will not allow vore actions, if yes will, ect...)

**Pull request closed without merging**
