### PR TITLE
Upstream Merge 08/05/2024

### PR DESCRIPTION
**Pull request by FoxxoTrystan**
# Description

Upstream Merge from EE: https://github.com/Simple-Station/Einstein-Engines/

Solus told me that merge is very stable and i could agree there was not was a lot of conflicts except for role timers.

THIS PR WILL NEED DISCUSSION AS ROLE TIMERS ARE HEAVLY CHANGED IN THIS MERGE, PLEASE CHECK FILE AND DISCUSS IT HERE OR ON DISCORD.

---

# TODO

- [x] Discuss about the Role/Requirement and set the one set on.

---

# Changelog

:cl:
- add: Upstream Merge

### CODE REVIEW

**Comment by Fansana** [comment]
All of the changes to role timers need to be reverted.

**Comment by Fansana** [comment]
This is a good opportunity to fix the outstanding role timers as well. There is no point in forcing people to play days worth of time just to play in the role they want.

**Comment by FoxxoTrystan** [comment]
> All of the changes to role timers need to be reverted.

This is why i left the "Need Discussion", will update the merge with new update and revert the timers, well just the numbers.

**Comment by Fansana** [comment]
I can update them later today.

**Comment by FoxxoTrystan** [comment]
> I can update them later today.

Alright.

**Comment by FoxxoTrystan** [comment]
> All of the changes to role timers need to be reverted.

Reverted timers, ready to merge!

**Comment by Fansana** [comment]
Sorry didn't get to this yet. I'll get it down asap.

**Comment by FoxxoTrystan** [comment]
> Sorry didn't get to this yet. I'll get it down asap.

I changed the value, feel free to check it but i reverted to what its is currently.

**Comment by Fansana** [comment]
Playtimes are updated for most things. However I found this
image
Is supposed to be this way? I thought the default was 500 now.

**Comment by FoxxoTrystan** [comment]
> Playtimes are updated for most things. However I found this image Is supposed to be this way? I thought the default was 500 now.

Il give it a quick look, but i think its normal.

**Comment by FoxxoTrystan** [comment]
as Oracle got changed but not the glimmer system

**Review by Fansana — APPROVED** [review]

**Comment by Fansana** [comment]
Please don't deploy, let the auto deploy handle it, okay?

**Comment by Fansana** [comment]
Welp I guess I need to stay then.

**Pull request merged**
