### PR TITLE
Rouny Sprite Update

### PR DESCRIPTION
**Pull request by fenndragon**
# Description

Quick update to the Rouny texture to have more depth

---

# Changelog

:cl:

- tweak: Updated the Rouny Sprite

### CODE REVIEW

**Review by FoxxoTrystan — CHANGES_REQUESTED** [review]
Please edit the PR Description, Changlog, Ect...

**Review by Memeji — APPROVED** [review]

**Review by FoxxoTrystan — CHANGES_REQUESTED** [review]
This description is again not following the correct format, there no changlog heres at all.

**Review by Memeji — CHANGES_REQUESTED** [review]
As Trystan requested, follow the correct format.

**Comment by ShatteredSwords** [comment]
@FoxxoTrystan @Memeji 
CL looks all good now!

**Review by FoxxoTrystan — APPROVED** [review]

**Pull request merged**
