### PR TITLE
Revert #6 "Latest Experimental Psychics"

### PR DESCRIPTION
**Pull request by ShatteredSwords**
# Description

This is a reversion of PR #6 to make merging upstream possible. I am doing this under the guidance of @DangerRevolution to see which files are conflicting.
This also includes a revert of PR #66  by @FoxxoTrystan 
I have also recieved the guidance of @VMSolidus in the later half.

---

# TODO

- [X] Fix all conflicts?

---

🆑 ShatteredSwords and FoxxoTrystan

- remove: Experimental Psychic Playtest
- remove: Psionic Refractor Changes

### CODE REVIEW

**Comment by Fansana** [comment]
I want a deploy stop when this is merged until the psyonics changes are back in the game.

**Comment by ShatteredSwords** [comment]
> I want a deploy stop when this is merged until the psyonics changes are back in the game.

That's the idea, that is why this is a draft ATM

**Comment by ShatteredSwords** [comment]
Gonna get this out of draft so I can specifically test it

**Comment by ShatteredSwords** [comment]
I will be working with Fansana to remove the conflicting files.

**Comment by FoxxoTrystan** [comment]
Psonic will still be in the game, nothing really will have change as this is a experimental feature, issue is that we cannot upstream merge until this is done.

**Review by Memeji — CHANGES_REQUESTED** [review]
Multiple tests have failed, please have those tests pass.

**Review by FoxxoTrystan — CHANGES_REQUESTED** [review]
Test fails are legits, this will need to be resolved, and we will need to make sure nothing broke.

**Comment by ShatteredSwords** [comment]
Yes, working on the files right now. Also considering just reverting all the way back to 6, and then PRing everything without 6, just to see what happens.

**Comment by VMSolidus** [comment]
image

Easy fix, revert *this specific line*

**Comment by ShatteredSwords** [comment]
I am not completely sure if everything is reverted, but this seems to build without the conflicting files. Please look over it and make sure I'm not forgetting something or if it doesn't need any more editing.

**Comment by FoxxoTrystan** [comment]
I will test it when i wake up.

**Review by FoxxoTrystan — APPROVED** [review]
During test, this seem ready.

Do not merge, i will handle it, aka i left a tag for it.

**Comment by FoxxoTrystan** [comment]
This PR has been merged with https://github.com/Fansana/floofstation1/pull/114

Meaning its will be added at the same time as the upstream merge.

**Pull request closed without merging**
