### PR TITLE
Floof Loadout Update

### PR DESCRIPTION
**Pull request by ShatteredSwords**
# Description

This PR lowers the cost of many of the Floof loadout items, and smushes all loadouts into one big list so you can't take multiple. I had to choose between the possibility of having a merge conflict that could be solved using find and replace, and having a merge conflict that you would have to manually solve. Anyways, enjoy the duct tape and the bucket of nails. You can't have multiple of a prototype so I had to get creative. This essentially nullifies most of the character item groups from upstream in favor of having our own. The good thing is, less shit you'd have to manually solve in the first place.

Oh and also I added suspenders for whoever requested them. They are purely cosmetic. Feel free to take both if you'd like to.

Please just ping me if this will cause a merge conflict in the future, I could easily solve whatever it is to match upstream with find and replace.

---

# Changelog

:cl:
- add: Suspenders are now in loadouts.
- tweak: Loadouts items from Floof are a lot cheaper, but you cannot take an extra change of clothes.

### CODE REVIEW

**Comment by Memeji** [comment]
Going to look over this carefully sometime this weekend.

**Comment by Fansana** [comment]
Gonna be honest I kinda prefer being able to pick multiple items. For clothing it accessories I think it makes sense that you can only pick one. I haven't had a chance to look at this in detail yet.

**Comment by ShatteredSwords** [comment]
> Gonna be honest I kinda prefer being able to pick multiple items. For clothing it accessories I think it makes sense that you can only pick one. I haven't had a chance to look at this in detail yet.

Items have not been touched, it's all clothing. I have yet to add in items and item groups.

**Comment by Memeji** [comment]
To clarify:
-I see a lot of items now cost 0.
-There's the second loadout slot for these items.

**Comment by ShatteredSwords** [comment]
> To clarify: -I see a lot of items now cost 0. -There's the second loadout slot for these items.

Yes, this was what loadouts V3 was meant for actually. The cost of things were supposed to go down to 0 or near 0, but you cannot take extras
Not sure what you mean by the second point.

**Review by Memeji — APPROVED** [review]

**Comment by ShatteredSwords** [comment]
Created localization for this PR in terms of item groups. I will be working on job loadouts changes later on, but for now, we have the basic loadouts.

**Comment by ShatteredSwords** [comment]
I can confirm that the localization works after testing

**Pull request merged**
