### PR TITLE
Axel and Luna

### PR DESCRIPTION
**Pull request by neuPanda**
Added Axel's Ale, The Cute Captain, Jenn in Tonic, and Hallelujah

need somebody who can sprite to be able to help with this
no additional sprite needed for Hallelujah,  this drink is intended to be very simple in its representation

:cl:
- add: Added 4 new drinks: Axel's Ale, The Cute Captain, Jenn in Tonic, Hallelujah

### CODE REVIEW

**Comment by Memeji** [comment]
Do you wanna keep this open until you have sprites done?

**Comment by neuPanda** [comment]
they have basic sprites in their glasses, but not the advanced texturing.  i don't know how to go about that. for the finer details

**Comment by Memeji** [comment]
I'd prefer if everything was done when we merge it.
I'll look into this further on the weekend.

**Comment by neuPanda** [comment]
> I'd prefer if everything was done when we merge it. I'll look into this further on the weekend.

technically it is done, however somebody has offered to improve the sprites

**Comment by flyingkarii** [comment]
Just a general question, does Floof allow adding two entirely separate mechanics in one PR? 'Cause this has drinks and the kiss and lick interactions in the same one.

**Comment by Fansana** [comment]
> Just a general question, does Floof allow adding two entirely separate mechanics in one PR? 'Cause this has drinks and the kiss and lick interactions in the same one.

That is actually a very good point. Please split this up into multiple PRs. The Interactions can stay in the same PR just the drinks should go into it's own PR. Makes reviewing easier too.

**Comment by Mnemotechnician** [comment]
It seems like the PR was made on an incorrect branch. It contains commits from #179 and probably downstreams from it.

**Comment by neuPanda** [comment]
> It seems like the PR was made on an incorrect branch. It contains commits from #179 and probably downstream from it.

ah, i think i had based this on the wrong branch i thought i had selected to use the main branch but i must have forgotten to change it or it didn't change like i thought it had before i created the next one.  i will re-base.  thank you

**Comment by neuPanda** [comment]
damit git stop being a pain in my ass

**Comment by neuPanda** [comment]
> could you improve the change log? Like adding the names of the drinks?

I could do that,  i just figured it would be better to not clog the log

**Comment by Mnemotechnician** [comment]
`- add: Added 4 new drinks: <... names>` would be more appropriate.

**Review by FoxxoTrystan — CHANGES_REQUESTED** [review]
Please make a better changelog.

**Comment by neuPanda** [comment]
> Please make a better changelog.

what would you like me to add?

**Comment by FoxxoTrystan** [comment]
Look at @Mnemotechnician reply.

**Review by ShatteredSwords — APPROVED** [review]
All recipes work after playtesting

**Review by FoxxoTrystan — APPROVED** [review]

**Review by Memeji — APPROVED** [review]

**Pull request merged**
