### PR TITLE
Consent UI Generated

### PR DESCRIPTION
**Pull request by FoxxoTrystan**
# Description

This PR does not include a changlog as its does not change anything gameplay wise.

For devs, this makes so consent options in the UI are auto-generated by the prototype making it more easy to handle consent options as its generated correctly, also untangle some tiny messes and make the UI way more pretty.

---

<details><summary><h1>Media</h1></summary>
<p>

image
image

</p>
</details>

### CODE REVIEW

**Review by fenndragon — CHANGES_REQUESTED** [review]
A change log should still be necessary for visual/backend UI changes. Those aren't just for the players.

**Comment by Memeji** [comment]
> A change log should still be necessary for visual/backend UI changes. Those aren't just for the players.

Changelogs are specifically for players.

**Comment by FoxxoTrystan** [comment]
No changelogs are needed as this changes nothing for the players directly.

**Comment by sleepyyapril** [comment]
Is the idea for this being able to do something like _consentManager.GetConsentStatus("key"), similar to ccvars?

**Comment by FoxxoTrystan** [comment]
> Is the idea for this being able to do something like _consentManager.GetConsentStatus("key"), similar to ccvars?

This only changes Consent UI Aspect, not serverside, currently you need to do this:

_consent.HasConsent(uid, "key")

**Review by Memeji — APPROVED** [review]

**Comment by sleepyyapril** [comment]
> > Is the idea for this being able to do something like _consentManager.GetConsentStatus("key"), similar to ccvars?
> 
> This only changes Consent UI Aspect, not serverside, currently you need to do this:
> 
> _consent.HasConsent(uid, "key")

Right, but the goal is similar, which is what I meant. Amazing work.

**Pull request merged**
