### PR TITLE
Ghost Role Bar

### PR DESCRIPTION
**Pull request by ShatteredSwords**
# Description

Adds a bar that can only be spawned by admins, and only admins. This is for those shifts where everyone is dying and/or the round is boring. If you're an admin reading this, you can load this map using /loadmap (any map number not in use here) /maps/Floof/admin_only/ghost_bar.yml , and then you need to initialize the map with /mapinit (the map number you chose)
Ghost roles are already mapped in, no need to do anything else unless you'd like to. Please see your local heads of staff for the rules on spawning this.

---

<details><summary><h1>Media</h1></summary>
<p>

Bar and Bar Dorm, Medical Area
Arcade Area, D&D area, Chef Dorm
Kitchen and Botany Area, Atmos and Power
UwU

</p>
</details>

---

# Changelog

:cl:
- add: Added admin-spawnable-only map with ghost roles.

### CODE REVIEW

**Comment by ShatteredSwords** [comment]
Rare test W

**Comment by Fansana** [comment]
Could provide a picture on what the map looks like?

**Comment by ShatteredSwords** [comment]
> Could provide a picture on what the map looks like?

Is there any way to render it as a whole picture? Or do you want me to take screenshots?

**Comment by ShatteredSwords** [comment]
Do not merge this yet, fixgridatmos is being weird.

**Comment by Fansana** [comment]
screenshot would be fine

**Comment by ShatteredSwords** [comment]
@FoxxoTrystan Please put this on Do Not Merge status as it requires VM to PR a fix he may or may not have forgot about

**Comment by ShatteredSwords** [comment]
There are still issues with atmos, please do not merge this until it is fixed.

**Comment by ShatteredSwords** [comment]
today is the day that I see if this bitch works

**Comment by ShatteredSwords** [comment]
@Fansana @FoxxoTrystan @Memeji It works! Screenshots included in the media tab.

**Review by Fansana — APPROVED** [review]

**Pull request merged**
