### PR TITLE
Map Addition Kettle

### PR DESCRIPTION
**Pull request by Dunrab**
# Description

Add Kettle as a playable map for mid to high pop. This station dose not include a TEG due to atmos being separate from engineering. However, engineers have a few options for power such as a Tesla, AME and the solars have been beefed up due to the lack of a TEG. If engineering wanted to they could work with logi to order more solars and run the station off of solar power if they so choose or just stick to the tesla.

The maps includes all standard jobs for departments and I added a room for a psychologist and reporters so that anyone who likes playing those jobs can play them. I also mapped two shadowkin portals and set the job amount of Anomaly's to be four but that can be tweaked as needed.

I did not add Kettle to the map pool as I'm not sure if there is a want to test the map further than just me testing it on my own.

---

# TODO

- [x] Add missing things for epi (such as prober and mantis jobs)
- [x] Add room for reporters
- [x] Add room for psychologist
- [x] Add Cryo sleep since this map did not have any
- [x] Add Prisoner jobs and their cryosleep pods
- [x] Make sure arrivals & evac dock to the station properly
- [x] Upload the kettle.yml for the jobs 

---

<details><summary><h1>Media</h1></summary>
<p>

Kettle Map Render

</p>
</details>

---

# Changelog
:cl:
- add: Added Kettle as a mid pop map

### CODE REVIEW

**Review by FoxxoTrystan — CHANGES_REQUESTED** [review]
Test fails valid.

Dont forget to add your map in the Intergration Test.

[PostMapInitTest.cs](https://github.com/Fansana/floofstation1/blob/master/Content.IntegrationTests/Tests/PostMapInitTest.cs)

**Comment by Dunrab** [comment]
ah first time I have  added a new map, just added it will keep that in mind for the future

**Review by FoxxoTrystan — CHANGES_REQUESTED** [review]
Test Fails is valid, please check the test fail and fix the issue.

**Review by Memeji — APPROVED** [review]
Curious to test this map out!

**Comment by Dunrab** [comment]
its one of my favorite older maps im curious to see if engineering/atmos will build the "bridge" between medbay and the bar like we used to see on wizden all time and im also curious how everyone will like or dislike atmos being separate from engineering.

**Pull request merged**
