### PR TITLE
Round Start Security Magbots

### PR DESCRIPTION
**Pull request by ProphetCrow**
# Description
This is an expansion / overwrite to https://github.com/Fansana/floofstation1/pull/335 . I attempted to reach out to the original creator over discord, however, they appear to have left the community and the message did not go thru. 

The overall goal of this PR is to make security magboots more accessible round start. This PR aims to put a pair of magboots in every security hardsuit filled locker, including Corpsmen, Warden, HoS, and the normal security suit storage lockers. 

Why? I believe security should have this resource round start. Delta-P from spacing and lubebombs can sometimes be impossible to deal with as security, and other departments that have access to space suits, such as salvage and engineering, already start with magboots in their lockers. I dont believe its a logical stretch to give it to security, who may have one of the highest needs for this kind of item.
As it currently stands, these items are locked behind a techfab recipe, and that puts the urgency to print these boots in the hands of the warden or head of security, depending on the map. These players may not even realize these items are even in the game, or you may often run into games where there is no warden or a HoS; making ready access to these items impossible. 
In addition, DeltaV released this version of the magboots on their server to a widely positive review. My PR expands upon this release and reuses the sprite from their fork, which is my resprite that I personally made to match the uniforms of the security officers. 

Potential concerns: I attempted to add a delayuse component on the boots to prevent people from robustly spamming the slip-proof feature while minimizing the 20% movement speed reduction, but I wasnt able to get it to work at my junior level of programming so I opt'd to leave it alone. I was able to identify it could be related to the ToggleClothing system but its currently above my skill level. 
Seeing how this playerbase is more MRP, I personally dont believe we will run into a situation of a player abusing the slip proof function of the magboots to metagame security that often, but I do know this was a potential balance concern. 
Overall, I believe the addition of these boots are a net positive to the security department. I believe their introduction into suitstorage lockers is well overdue. 

---

image
image
image

---

:cl: Crow
- tweak: Adjusted security magboots to spawn in appropriate suit storage lockers

### CODE REVIEW

**Comment by Fansana** [comment]
I'm personally against this, the shoes at this point offer an armor bonus which would make them a must take. If they are available round start they have to lose this bonus.

**Comment by fenndragon** [comment]
Normally I would say either it's magboots or armor. But no other boot in the game to my knowledge has any form of armor. I agree with fasana on this one

**Comment by BluCottonCandy** [comment]
The thing is security should not be wearing Magboots/hard suits (excluding warden and HOS) unless they are required. 

The armor they add is insignificant, and if we tried to add security gas masks (which do also have armor) you all would have the same complaint, yet no one's ever had an issue with them as they truly add no bonus. 

I am all for this PR because not having them round start is stupid.

**Comment by fenndragon** [comment]
> The thing is security should not be wearing Magboots/hard suits (excluding warden and HOS) unless they are required.
> 
> The armor they add is insignificant, and if we tried to add security gas masks (which do also have armor) you all would have the same complaint, yet no one's ever had an issue with them as they truly add no bonus.
> 
> I am all for this PR because not having them round start is stupid.

we would  not have the same complaint, other armored leg pieces have been denied for the same reason, and actually having magboots and hardsuits is not actually against any rules or guidelines, it's just not general practice for any of the above to have hardsuits when in code green.

**Comment by ProphetCrow** [comment]
> I'm personally against this, the shoes at this point offer an armor bonus which would make them a must take. If they are available round start they have to lose this bonus.

The armor bonus was stripped, I overwritten the original PR. Ill double check the code though.

**Review by Fansana — APPROVED** [review]

**Comment by VividPups** [comment]
And please do not removed the SESWC

**Comment by VividPups** [comment]
also have this been tested on VOX so that it lines up correctly with them

**Review by FoxxoTrystan — APPROVED** [review]

**Review by FoxxoTrystan — CHANGES_REQUESTED** [review]
/Prototypes/Floof/Recipes/Lathes/security.yml(18,3)  Field "parent" not found in "Content.Shared.Research.Prototypes.LatheRecipePrototype".

Fix valid test fails

**Comment by Fansana** [comment]
Dunno why the test is complaining about the saltern docking but I think it doesn't matter.

**Review by Memeji — APPROVED** [review]

**Pull request merged**
