### PR TITLE
Selective Merge 2024-11-04

### PR DESCRIPTION
**Pull request by Mnemotechnician**
# Description
I was told by trystan it'd fine to do a selective upstream merge, so here we go.

Note: any of those changes can be reverted on demand. Hail git.

## This includes the following new features:
- [Feat: Port Delta-V Glimmer Wisps (#1125)](https://github.com/simple-station/einstein-engines/pull/1125)
- [[Feat] Telescopic Batons (#1144)](https://github.com/simple-station/einstein-engines/pull/1144)
- [Feat: energy bolas (#1135)](https://github.com/simple-station/einstein-engines/pull/1135)
- [Pyrokinetic Flare Power (#1138)](https://github.com/simple-station/einstein-engines/pull/1138)
- [Psionic Familiar Powers (#1146)](https://github.com/simple-station/einstein-engines/pull/1146)
- [[Feature] Clicking on Health Alerty Now Displays Health State (#1139)](https://github.com/simple-station/einstein-engines/pull/1139)
- [Some new sprites for dept heads, lockers, and crates (#1174)](https://github.com/simple-station/einstein-engines/pull/1174)
- ~~[More Sec Loadout Guns (#1158)](https://github.com/simple-station/einstein-engines/pull/1158)~~ (new loadouts commented out, restyle of the existing loadouts preserved)
- [Trait Modify Factions (animal lover trait) (#955)](https://github.com/simple-station/einstein-engines/pull/955)
- Update to RobustToolbox 227.0.0

## This also includes a lot of fixes, some of which may or may not have been cherry-picked already, namely:
- Traitors and their familliars having the syndicate faction
- Cocoon, penlight, and voice mask fixes
- Fix for cybereyes revealing the name of their user
- Fix for invalid markup tags in news and a missing deflect locale
- Fix for radial menu icons in quick construction

## This does NOT include:
- The controversial changes to cargo and salvage
- Any map changes - floof now has its own map pool, and only upstream map files are affected.

# TODO
- [x] Test this
- [x] Fill the new Janitor and Bartender closets
- [x] Make the Uranium Crate use the new Uranium Crate sprite
- [x] Rename the silver crate to be "Silver Crate". As it is called "Gold Crate".

# Changelog
:cl:
- add: Merged some of the upstream changes. See the Einstein-Engines tab for more details.

### CODE REVIEW

**Comment by Mnemotechnician** [comment]
I think I submitted the PR to the wrong branch :trollface:

**Comment by Memeji** [comment]
The 1135 shows energy bolas, does it include telescopic batons as well?

**Comment by Mnemotechnician** [comment]
> The 1135 shows energy bolas, does it include telescopic batons as well?

Oops, I mixed them up, let me fix-

**Comment by Fansana** [comment]
No master was the right branch, we went back to the old system and instead are using a stable branch.

**Comment by FoxxoTrystan** [comment]
Where my merge upstream button, anywho please update this PR with the latest "Master" branch as there was some fixes for build/test.

**Comment by Mnemotechnician** [comment]
I did merge the latest changes, including the update to RT227.0.0. It compiles, but there are now some linter errors caused by duplicate FTL locales.

I'd fix them, but I am currently experiencing certain technical difficulties. NuGet refusing to work, git submodules being fucky, and more... I've already spent two hours trying to fix all of this; I'll try a different approach later and fix the errors if it succeeds later.

**Comment by Memeji** [comment]
Going over this, can you remove the Security Loadout Merge #1158?
We'll be going over security as a whole and we don't want to add the Python especially to the loadouts.

**Comment by Mnemotechnician** [comment]
> Going over this, can you remove the Security Loadout Merge #1158? We'll be going over security as a whole and we don't want to add the Python especially to the loadouts.

I'll comment the new loadouts out instead, because that PR includes both new prototypes (which could potentially be balanced for sec specifically), and changes to existing weapon loadouts.

**Review by Memeji — APPROVED** [review]

**Comment by Mnemotechnician** [comment]
I do ask you not to merge this until I and someone else get to test this PR. It's only today that I finally managed to resolve my issues with dotnet and managed to compile ss14 once again.

**Comment by Memeji** [comment]
> I do ask you not to merge this until I and someone else get to test this PR. It's only today that I finally managed to resolve my issues with dotnet and managed to compile ss14 once again.

Heard, we'll make sure not to merge it. Let us know when it's tested!

**Comment by Fansana** [comment]
doing a bunch of tests and it seems the gas analyser doesn't work

**Comment by Mnemotechnician** [comment]
> doing a bunch of tests and it seems the gas analyser doesn't work

Huh?

image

image

**Comment by Mnemotechnician** [comment]
Everything I could test was working fine so far.

**Comment by Memeji** [comment]
> doing a bunch of tests and it seems the gas analyser doesn't work

Can you elaborate on this issue, or see if it still occurs?

**Comment by Mnemotechnician** [comment]
It might or might not have been the BUI bug that prevented you from turning on the gas analyzer. The same bug that occurs with bags, consoles, and literally every entity that has a bound user interface. The fix for it is... uh... just a week away, in the december/january upstream merge I guess.

**Comment by Fansana** [comment]
Okay we narrowed it down, the gas analyzer doesn't activate when used on the pipe but you can activate it in your hand.

**Comment by Memeji** [comment]
> It might or might not have been the BUI bug that prevented you from turning on the gas analyzer. The same bug that occurs with bags, consoles, and literally every entity that has a bound user interface. The fix for it is... uh... just a week away, in the december/january upstream merge I guess.

To also clarify:
1. Activating in your hand brings up the UI.
2. Clicking on a pipe adds the pipe to the UI.

1. Clicking on the pipe while the analyzer's UI is off does not bring up the UI.
2. Activating it in your hand brings up the UI but it does NOT contain the pipe.
3. Right-clicking and selecting "Toggle UI" brings up the UI and DOES include the pipe.

**Comment by Fansana** [comment]
> r might not have been the BUI bug that prevented you from turning on the gas analyzer. The same bug that occurs with bags, consoles, and literally every entity that has a bound user interface. The fix for it is... uh... just a week away, in the december/january upstream merge I guess.

Is the fix for that already there?

**Comment by Mnemotechnician** [comment]
> Is the fix for that already there?

There was some PR to fix the bug specifically for inventories, I'm not sure if it also fixed that behavior for other BUIs

Worst case scenario is the fix may be apart of the second engine update (v227 -> v237), merging which requires also merging shitmed and breaking both game balance and every single system in the process

**Comment by Fansana** [comment]
image
two gold crates, one of them contains silver

**Comment by Fansana** [comment]
So the animal friend trait doesn't work at all.

**Comment by Fansana** [comment]
the new lockers are just empty

**Comment by Mnemotechnician** [comment]
> the new lockers are just empty

That's intentional, they are not [Filled].

**Comment by Memeji** [comment]
> > the new lockers are just empty
> 
> That's intentional, they are not [Filled]. We can add filled versions on the floof side, or wait for it to be done on ee.

I will want them filled before adding them here. As I heard with the Clown and Mime last time, it ended up with their lockers empty for a while.

**Comment by Fansana** [comment]
> > the new lockers are just empty
> 
> That's intentional, they are not [Filled]. We can add filled versions on the floof side, or wait for it to be done on ee.

ah that's okay then I'll just fill em myself

**Review by FoxxoTrystan — APPROVED** [review]

**Review by Fansana — APPROVED** [review]

**Comment by Fansana** [comment]
@Memeji I grant you the honor of merging, please double check that we didn't forget anything.

**Review by Memeji — APPROVED** [review]

**Pull request merged**
