### PR TITLE
Remove Bionic Arm

### PR DESCRIPTION
**Pull request by FoxxoTrystan**
# Description

Remove the Bionic arm

Change suggested.

---

# Changelog

:cl:
- remove: Removed Bionic Arm

### CODE REVIEW

**Comment by BluCottonCandy** [comment]
So what exactly is the reason for the removal? 
I've been told it's due to "LRP behavior" 

I don't understand what LRP behavior you are seeing done with it. 
Personally I have used it for RP purposes only. 
It's a slow action, arguably worse than Jaws of life because it leaves your prints behind, and getting jaws of life from Epi honestly of not at all difficult. 
While yes SOP is supposed to stop departments handing out tools, it doesn't. 

If anything, removing these will only encourage more power gaming.

**Comment by Memeji** [comment]
Primarily due to the fact it makes no noise, making it a silent and free round-start JoL.
It also can be used by Gladiators, which are technically supposed to be prisoners and therefore not allowed to have them.
It can also open any door since its a JoL as a trait: Vault, Command, Sec, powered or not.

It is more so being "disabled" until these issues are fixed due to many reports of the it being abused.
Once it has a sound added and Gladiators are stopped from using it, as well as any other discussion regarding balance, it will be back.

**Comment by BluCottonCandy** [comment]
> Primarily due to the fact it makes no noise, making it a silent and free round-start JoL. It also can be used by Gladiators, which are technically supposed to be prisoners and therefore not allowed to have them. It can also open any door since its a JoL as a trait: Vault, Command, Sec, powered or not.
> 
> It is more so being "disabled" until these issues are fixed due to many reports of the it being abused. Once it has a sound added and Gladiators are stopped from using it, as well as any other discussion regarding balance, it will be back.

While I understand that, how are phyonics not being removed due to the same concerns? 
They are infinitely more powerful, prisoners are and to have them, and they can even stack to be more powerful

That's where I'm finding the disconnect in how this is truly such an issue, compared to phyonics which I'm not hearing complaints about, even though there very much abused.

**Comment by Memeji** [comment]
Psionics have a huge system with it. I am planning on addressing them too, if there are specifically any powers that you know of that are too powerful, I can jump-start with a list for my investigation.

Compared to the Bionic arms, which only gives you the JoL component, it is a different beast.

**Comment by VividPups** [comment]
> Primarily due to the fact it makes no noise, making it a silent and free round-start JoL. It also can be used by Gladiators, which are technically supposed to be prisoners and therefore not allowed to have them. It can also open any door since its a JoL as a trait: Vault, Command, Sec, powered or not.
> 
> It is more so being "disabled" until these issues are fixed due to many reports of the it being abused. Once it has a sound added and Gladiators are stopped from using it, as well as any other discussion regarding balance, it will be back.

But you are able to add noise to it when it is being used (like Vore, and Ripley) 
also, you can make it where some doors (I would say the Vault doors) Are immune to it or Command doors since TECHIONLLY has antihacking stuff in it we could make It where they "have reinforced antislip railing" to make it take longer for it to open 

Also, there are already Loadouts that have it to where you can't be this in order to use it I feel like most of these problems can be fix through additional yml edits versus removing it. 
wouldn't those be better then just removing them

**Comment by VividPups** [comment]
> Psionics have a huge system with it. I am planning on addressing them too, if there are specifically any powers that you know of that are too powerful, I can jump-start with a list for my investigation.
> 
> Compared to the Bionic arms, which only gives you the JoL component, it is a different beast.

Mass sleep is the biggest one. sense Mindswap has already been nerf (Mindshield implant should probably be added to the syndi uplink)

**Comment by Memeji** [comment]
> > Primarily due to the fact it makes no noise, making it a silent and free round-start JoL. It also can be used by Gladiators, which are technically supposed to be prisoners and therefore not allowed to have them. It can also open any door since its a JoL as a trait: Vault, Command, Sec, powered or not.
> > It is more so being "disabled" until these issues are fixed due to many reports of the it being abused. Once it has a sound added and Gladiators are stopped from using it, as well as any other discussion regarding balance, it will be back.
> 
> But you are able to add noise to it when it is being used (like Vore, and Ripley) also, you can make it where some doors (I would say the Vault doors) Are immune to it or Command doors since TECHIONLLY has antihacking stuff in it we could make It where they "have reinforced antislip railing" to make it take longer for it to open
> 
> Also, there are already Loadouts that have it to where you can't be this in order to use it I feel like most of these problems can be fix through additional yml edits versus removing it. wouldn't those be better then just removing them

Yes, if I had the time and the space to do so.
At the moment, testing needs to be fixed (done finally I hope), and then go through the current PRs.
Then I have to update a few systems.

To be honest, if I'm not surprised by any sudden issues (knock on wood), I can skip the disabling and add the fix this week.

**Comment by VividPups** [comment]
> > > Primarily due to the fact it makes no noise, making it a silent and free round-start JoL. It also can be used by Gladiators, which are technically supposed to be prisoners and therefore not allowed to have them. It can also open any door since its a JoL as a trait: Vault, Command, Sec, powered or not.
> > > It is more so being "disabled" until these issues are fixed due to many reports of the it being abused. Once it has a sound added and Gladiators are stopped from using it, as well as any other discussion regarding balance, it will be back.
> > 
> > 
> > But you are able to add noise to it when it is being used (like Vore, and Ripley) also, you can make it where some doors (I would say the Vault doors) Are immune to it or Command doors since TECHIONLLY has antihacking stuff in it we could make It where they "have reinforced antislip railing" to make it take longer for it to open
> > Also, there are already Loadouts that have it to where you can't be this in order to use it I feel like most of these problems can be fix through additional yml edits versus removing it. wouldn't those be better then just removing them
> 
> Yes, if I had the time and the space to do so. At the moment, testing needs to be fixed (done finally I hope), and then go through the current PRs. Then I have to update a few systems.
> 
> To be honest, if I'm not surprised by any sudden issues (knock on wood), I can skip the disabling and add the fix this week.

May I suggest a Nerf for the mass sleep is it to not be instant but make it work like the smoke effect (it is in effect for admins to used) to cause a like cloud of the gas instead so people with internals on can be immune to it

**Comment by Memeji** [comment]
> > > > Primarily due to the fact it makes no noise, making it a silent and free round-start JoL. It also can be used by Gladiators, which are technically supposed to be prisoners and therefore not allowed to have them. It can also open any door since its a JoL as a trait: Vault, Command, Sec, powered or not.
> > > > It is more so being "disabled" until these issues are fixed due to many reports of the it being abused. Once it has a sound added and Gladiators are stopped from using it, as well as any other discussion regarding balance, it will be back.
> > > 
> > > 
> > > But you are able to add noise to it when it is being used (like Vore, and Ripley) also, you can make it where some doors (I would say the Vault doors) Are immune to it or Command doors since TECHIONLLY has antihacking stuff in it we could make It where they "have reinforced antislip railing" to make it take longer for it to open
> > > Also, there are already Loadouts that have it to where you can't be this in order to use it I feel like most of these problems can be fix through additional yml edits versus removing it. wouldn't those be better then just removing them
> > 
> > 
> > Yes, if I had the time and the space to do so. At the moment, testing needs to be fixed (done finally I hope), and then go through the current PRs. Then I have to update a few systems.
> > To be honest, if I'm not surprised by any sudden issues (knock on wood), I can skip the disabling and add the fix this week.
> 
> May I suggest a Nerf for the mass sleep is it to not be instant but make it work like the smoke effect (it is in effect for admins to used) to cause a like cloud of the gas instead so people with internals on can be immune to it

Sure, make another suggestions thread in the discord for psionic balancing so I can keep track of the discussion.

**Pull request closed without merging**
