### PR TITLE
Nonlethal Weapon for an ONI 

### PR DESCRIPTION
**Pull request by VividPups**
# Description

One shift as captain a security corpsman approached me, and they gave me a problem that was really an oversight, So far there isn't a legal non-sec weapon for Oni bartenders to have to protect their bars, as we know Bartenders come with nonlethal weapons (except for the knife on the Mosin) this is to help that problem,  I pretty much pull all the things from when I made this in Frontier. however, I change the damage type to be stun only. so far the stun baton takes about 3 hits to stun someone,  the brass knuckles take 6 to stun someone but it is a bit faster 

this technically adds 3 different types
Crassnuckles (it is a whoopie cushion brass knuckles) for clowns 
improvise BrassKnuckles 
and the official one for Oni's 

image
image 
image

# Changelog

:cl:
- add: brass-knuckles to the oni loadout 
- add: can now craft brass knuckles as a stun weapon
- add: the crass-knuckles

### CODE REVIEW

**Comment by VividPups** [comment]
The only problem I am having is that I can't seem to get the Crafting recipe to work with the crassknuckles, would ask for help with that

**Review by FoxxoTrystan — CHANGES_REQUESTED** [review]
Test fails are valid.

**Comment by Memeji** [comment]
> The only problem I am having is that I can't seem to get the Crafting recipe to work with the crassknuckles, would ask for help with that

What is the issue?

**Comment by VividPups** [comment]
> > The only problem I am having is that I can't seem to get the Crafting recipe to work with the crassknuckles, would ask for help with that
> 
> What is the issue?

It just keep saying that they don't have the materials

**Comment by VividPups** [comment]
> Test fails are valid.

Looks like it's from the behonker and I didn't do anything to it

**Comment by Fansana** [comment]
they are to expensive put them at less then 17 spesos

**Comment by Fansana** [comment]
Tested this just now and they feel a tad strong.

**Comment by VividPups** [comment]
> Tested this just now and they feel a tad strong. Mostly the stamina damage.

It's for a bartender oni only,  stun baton is 3 hits,  these should be 6 hits

**Comment by VividPups** [comment]
I also am not sure how to fix the behonkers

**Comment by FoxxoTrystan** [comment]
Tests fails are valid, look into them to how to fix them.

**Comment by VividPups** [comment]
> Tests fails are valid, look into them to how to fix them.

that doesn't help me at all trystan

**Comment by fenndragon** [comment]
> Tests fails are valid, look into them to how to fix them.

The test fail is the error code 1 which is usually a false positive. What makes this one a valid fail?

**Comment by Memeji** [comment]
Reason for test fail:

1)   WeaponBrassKnucklesWhoopie increases in price after decomposed into raw materials
Assert.That(sumPrice, Is.LessThanOrEqualTo(price))
  Expected: less than or equal to 30.0d
  But was:  100.0d

  2)   WeaponBrassKnucklesImprovised increases in price after decomposed into raw materials
Assert.That(sumPrice, Is.LessThanOrEqualTo(price))
  Expected: less than or equal to [17](https://github.com/Fansana/floofstation1/actions/runs/11945946236/job/33299490715?pr=371#step:10:18).500011920928955d
  But was:  100.0d

  3)   WeaponBrassKnuckles increases in price after decomposed into raw materials
Assert.That(sumPrice, Is.LessThanOrEqualTo(price))
  Expected: less than or equal to 17.50001[19](https://github.com/Fansana/floofstation1/actions/runs/11945946236/job/33299490715?pr=371#step:10:20)20928955d
  But was:  100.0d

So the brass knuckles, when turned into raw materials, results in materials that cost more than the weapon.
This means it can be a free money generator, according to the system :p

**Comment by fenndragon** [comment]
> Tests fails are valid, look into them to how to fix them.

Nevermind I found it. You need to raise the price of the brass knuckles as the materials to make it are worth more than the knuckles themselves. If you buy them then break them down you make a profit.

**Comment by fenndragon** [comment]
I

> Reason for test fail:
> 
> 1. WeaponBrassKnucklesWhoopie increases in price after decomposed into raw materials
>    Assert.That(sumPrice, Is.LessThanOrEqualTo(price))
>    Expected: less than or equal to 30.0d
>    But was:  100.0d
> 2. WeaponBrassKnucklesImprovised increases in price after decomposed into raw materials
>    Assert.That(sumPrice, Is.LessThanOrEqualTo(price))
>    Expected: less than or equal to [17](https://github.com/Fansana/floofstation1/actions/runs/11945946236/job/33299490715?pr=371#step:10:18).500011920928955d
>    But was:  100.0d
> 3. WeaponBrassKnuckles increases in price after decomposed into raw materials
>    Assert.That(sumPrice, Is.LessThanOrEqualTo(price))
>    Expected: less than or equal to 17.50001[19](https://github.com/Fansana/floofstation1/actions/runs/11945946236/job/33299490715?pr=371#step:10:20)20928955d
>    But was:  100.0d
> 
> So the brass knuckles, when turned into raw materials, results in materials that cost more than the weapon. This means it can be a free money generator, according to the system :p

Fuck you beat me to it

**Comment by Memeji** [comment]
> I
> 
> > Reason for test fail:
> > 
> > 1. WeaponBrassKnucklesWhoopie increases in price after decomposed into raw materials
> >    Assert.That(sumPrice, Is.LessThanOrEqualTo(price))
> >    Expected: less than or equal to 30.0d
> >    But was:  100.0d
> > 2. WeaponBrassKnucklesImprovised increases in price after decomposed into raw materials
> >    Assert.That(sumPrice, Is.LessThanOrEqualTo(price))
> >    Expected: less than or equal to [17](https://github.com/Fansana/floofstation1/actions/runs/11945946236/job/33299490715?pr=371#step:10:18).500011920928955d
> >    But was:  100.0d
> > 3. WeaponBrassKnuckles increases in price after decomposed into raw materials
> >    Assert.That(sumPrice, Is.LessThanOrEqualTo(price))
> >    Expected: less than or equal to 17.50001[19](https://github.com/Fansana/floofstation1/actions/runs/11945946236/job/33299490715?pr=371#step:10:20)20928955d
> >    But was:  100.0d
> > 
> > So the brass knuckles, when turned into raw materials, results in materials that cost more than the weapon. This means it can be a free money generator, according to the system :p
> 
> Fuck you beat me to it

heheheheheheheheheheeh am speedy

**Comment by VividPups** [comment]
> Reason for test fail:
> 
> 1. WeaponBrassKnucklesWhoopie increases in price after decomposed into raw materials
>    Assert.That(sumPrice, Is.LessThanOrEqualTo(price))
>    Expected: less than or equal to 30.0d
>    But was:  100.0d
> 2. WeaponBrassKnucklesImprovised increases in price after decomposed into raw materials
>    Assert.That(sumPrice, Is.LessThanOrEqualTo(price))
>    Expected: less than or equal to [17](https://github.com/Fansana/floofstation1/actions/runs/11945946236/job/33299490715?pr=371#step:10:18).500011920928955d
>    But was:  100.0d
> 3. WeaponBrassKnuckles increases in price after decomposed into raw materials
>    Assert.That(sumPrice, Is.LessThanOrEqualTo(price))
>    Expected: less than or equal to 17.50001[19](https://github.com/Fansana/floofstation1/actions/runs/11945946236/job/33299490715?pr=371#step:10:20)20928955d
>    But was:  100.0d
> 
> So the brass knuckles, when turned into raw materials, results in materials that cost more than the weapon. This means it can be a free money generator, according to the system :p

Thank you i don't know how to fully read the checkers yet and this does make since because This is techionally a port from frontier where they Adjust a bunch of prices

**Comment by VividPups** [comment]
I will have this completed within next two days

**Comment by VividPups** [comment]
Merge errors were fix

**Review by Fansana — APPROVED** [review]

**Pull request merged**
