### PR TITLE
Cryo Overhaul

### PR DESCRIPTION
**Pull request by neuPanda**
Description.
added 2 intermidiate chems
- SalicylicAcid
- Formaldehyde

added 2 Cryo Chems
-Traumoxadone (Brute Damages)
-Stelloxadone (Tox Damages)

modified existing cryo chems to be more viable yet still balanced improved efficiency of cryo chambers
- Cryox only heals blood loss and air loss damage on a body, now useable after death
- Alox now also heals cold damage
- Doxa now uses Phalanximine not UnstableMutagen works after death twice as effective
- Oppo now uses Formaldehyde not Cognizine

updated cryo guide book to show all cryo chems

modified body metabolism
- the body no longer only metabolizes 2 chems at once but all chems in the system
- restrictive logic still somewhat in tact to prevent poison power gaming max 3 toxins

modified cryopods
- cryopods now split chems and inject them independently rather than a mixed solution
- cryopods require 1/2 the amount of chems to do the same healing

:cl:
- add: new cryo chems
- tweak: old cryo chems
- fix: death
- remove: metabolism restrictions

### CODE REVIEW

**Comment by neuPanda** [comment]
wanted to get the PR started to make sure that checks pass and nothing fails.  i will get the description updated when i get home from dinner

**Comment by Memeji** [comment]
How dare you not have the description ready yet.

**Comment by XavierSomething** [comment]
As a person that plays medical in chemistry a lot, these changes are VERY overpowered for medical. I do understand that cryopods are severely underused when it comes to medical on Floof, but these would cause death to be trivialized when it comes to revivals. 

- With one fully potent aloe that gives you 10u of aloe, you can make 20u of Aloxadone to heal 120 of every burn damage, doubled to 240 since you double the chems in the cryopod, imagine how much you can heal with more than a single piece of Aloe.

- One galaxythistle, which could produce 10u of stellibelin (with a max yield of 25u of stellibelin), would heal 240 poison since 10u of stellibelin is needed for making 10u of stelloxadone, which heals 12 poison every unit, and with the cryo's doubling, would mean a single galaxythistle of lower-than-average quality can heal someone fully of poison. 

- Since 1u of silver is needed to make 3u of formaldehyde, and 1u of formaldehyde is needed for 3u of oppo, with one bar of silver, you get 10u of silver which turns into 90u of opporozidone. From my knowledge, this would be enough to heal a bloated corpse to fresh, but this amount can heal 2 bloated corpses to max since 90u of oppo becomes 180u with the cryopod change. This is still mildly balanced since 6 sheets of plasma is needed to create the 90u of oppo, but before, cognizine was the primary bottleneck as it required carpotoxin and siderlac, while plasma is usually available.

While yes, there are a lot of other chems in the recipe you need to make each of these recipes, they are all chemicals you can make with the resources you get with the chemvend, which can be restocked from Logistics. The primary bottleneck when it comes to chem making is stuff you need outside the chemvend, which is shown above that just a single piece of one of the items required can have a giant impact. The brute cryo chem doesn't even need any outside resources to make it! Primarily, the cryopod doubling chemicals put inside would make it incredibly easy to revive as long as you just have some of the materials above, which could have a negative impact on roleplay since death is a LOT less needed to be worried about.

**Comment by neuPanda** [comment]
> As a person that plays medical in chemistry a lot, these changes are VERY overpowered for medical. I do understand that cryopods are severely underused when it comes to medical on Floof, but these would cause death to be trivialized when it comes to revivals.
> 
> * With one fully potent aloe that gives you 10u of aloe, you can make 20u of Aloxadone to heal 120 of every burn damage, doubled to 240 since you double the chems in the cryopod, imagine how much you can heal with more than a single piece of Aloe.
> * One galaxythistle, which could produce 10u of stellibelin (with a max yield of 25u of stellibelin), would heal 240 poison since 10u of stellibelin is needed for making 10u of stelloxadone, which heals 12 poison every unit, and with the cryo's doubling, would mean a single galaxythistle of lower-than-average quality can heal someone fully of poison.
> * Since 1u of silver is needed to make 3u of formaldehyde, and 1u of formaldehyde is needed for 3u of oppo, with one bar of silver, you get 10u of silver which turns into 90u of opporozidone. From my knowledge, this would be enough to heal a bloated corpse to fresh, but this amount can heal 2 bloated corpses to max since 90u of oppo becomes 180u with the cryopod change. This is still mildly balanced since 6 sheets of plasma is needed to create the 90u of oppo, but before, cognizine was the primary bottleneck as it required carpotoxin and siderlac, while plasma is usually available.
> 
> While yes, there are a lot of other chems in the recipe you need to make each of these recipes, they are all chemicals you can make with the resources you get with the chemvend, which can be restocked from Logistics. The primary bottleneck when it comes to chem making is stuff you need outside the chemvend, which is shown above that just a single piece of one of the items required can have a giant impact. The brute cryo chem doesn't even need any outside resources to make it! Primarily, the cryopod doubling chemicals put inside would make it incredibly easy to revive as long as you just have some of the materials above, which could have a negative impact on roleplay since death is a LOT less needed to be worried about.


as a medic main, this is something i took into consideration.  
I can make the same argument that topicals trivialize death

that said, from an RP stand point, the use of 100lb of ointments mixed with a pile of ash (500 heat damage) stuffed inside of a body woven of Band-Aids (500 brute damage) only to be shocked to be brought back to life in perfect condition infuriates me.  that is such an immersion break for me that it become mechanics over roleplay and i hate it

things to keep in mind
this is not a fast heal, the cryo chamber just reduces resource costs of what is put into it yes, but it only heals a small amount per tick.  normal chems are much faster

there is only 1 cryo tube if any on most maps.  this means that when you have a flood of people you can only take care of one of them at a time via cryo.

the primary chems you will use for cryo would all require you to  request resources from out side of your department.  not that it is hard to ask bottony for aloe and galaxy thistle but when it comes to healing the dead who have died to burn or being spaced.  we are looking at extremely high damage levels..  so while yes that 1 aloe was able to heal 240 burn during testing,  it took 80 seconds to do it, and i still needed another 2 aloe plants before i could have revived my test dummy.

the chems that are used for damage that stops at death, ie tox and genetics.  those cryo meds now have negative effects that damage the body

finally.  fuck cloning.  I know a lot of people that their skin crawls when they are forced into a different body type.  it might not for everybody, but i have seen others, and even my self seethed with anger because when i was cloned i got a random re-role into a different race.

yes, oppo is made far more accessible.  that said the idea that cognazine kills off rot is again immersion breaking.  further in order to make a useful amount of oppo to have a reasonable  effect on the body you have to rely on so much space carp that you might be able to bring back A patient who is rotting.  this allows you to instead dedicate time to the mending or patients and clear out your morgue without having to hope that xenos attack so you can clone, or that salvage remembers to bring you caprs.  having played salvage on this server, none of the salvagers understood why i was collecting carp to take to medical, but med thanked me for bringing them carps as apparently there were rotting bodies they needed to take care of.

finally, this code change I will eventually be sending up to EE
in fact i have been personally asked
before i do that though, I want to get some play testing done to find a good balance.  see what else might need to be tweaked so that when it is given to the up streams it is balanced on all servers using it

**Comment by XavierSomething** [comment]
> > As a person that plays medical in chemistry a lot, these changes are VERY overpowered for medical. I do understand that cryopods are severely underused when it comes to medical on Floof, but these would cause death to be trivialized when it comes to revivals.
> > 
> > * With one fully potent aloe that gives you 10u of aloe, you can make 20u of Aloxadone to heal 120 of every burn damage, doubled to 240 since you double the chems in the cryopod, imagine how much you can heal with more than a single piece of Aloe.
> > * One galaxythistle, which could produce 10u of stellibelin (with a max yield of 25u of stellibelin), would heal 240 poison since 10u of stellibelin is needed for making 10u of stelloxadone, which heals 12 poison every unit, and with the cryo's doubling, would mean a single galaxythistle of lower-than-average quality can heal someone fully of poison.
> > * Since 1u of silver is needed to make 3u of formaldehyde, and 1u of formaldehyde is needed for 3u of oppo, with one bar of silver, you get 10u of silver which turns into 90u of opporozidone. From my knowledge, this would be enough to heal a bloated corpse to fresh, but this amount can heal 2 bloated corpses to max since 90u of oppo becomes 180u with the cryopod change. This is still mildly balanced since 6 sheets of plasma is needed to create the 90u of oppo, but before, cognizine was the primary bottleneck as it required carpotoxin and siderlac, while plasma is usually available.
> > 
> > While yes, there are a lot of other chems in the recipe you need to make each of these recipes, they are all chemicals you can make with the resources you get with the chemvend, which can be restocked from Logistics. The primary bottleneck when it comes to chem making is stuff you need outside the chemvend, which is shown above that just a single piece of one of the items required can have a giant impact. The brute cryo chem doesn't even need any outside resources to make it! Primarily, the cryopod doubling chemicals put inside would make it incredibly easy to revive as long as you just have some of the materials above, which could have a negative impact on roleplay since death is a LOT less needed to be worried about.
> 
> as a medic main, this is something i took into consideration. I can make the same argument that topicals trivialize death
> 
> that said, from an RP stand point, the use of 100lb of ointments mixed with a pile of ash (500 heat damage) stuffed inside of a body woven of Band-Aids (500 brute damage) only to be shocked to be brought back to life in perfect condition infuriates me. that is such an immersion break for me that it become mechanics over roleplay and i hate it
> 
> things to keep in mind this is not a fast heal, the cryo chamber just reduces resource costs of what is put into it yes, but it only heals a small amount per tick. normal chems are much faster
> 
> there is only 1 cryo tube if any on most maps. this means that when you have a flood of people you can only take care of one of them at a time via cryo.
> 
> the primary chems you will use for cryo would all require you to request resources from out side of your department. not that it is hard to ask bottony for aloe and galaxy thistle but when it comes to healing the dead who have died to burn or being spaced. we are looking at extremely high damage levels.. so while yes that 1 aloe was able to heal 240 burn during testing, it took 80 seconds to do it, and i still needed another 2 aloe plants before i could have revived my test dummy.
> 
> the chems that are used for damage that stops at death, ie tox and genetics. those cryo meds now have negative effects that damage the body
> 
> finally. fuck cloning. I know a lot of people that their skin crawls when they are forced into a different body type. it might not for everybody, but i have seen others, and even my self seethed with anger because when i was cloned i got a random re-role into a different race.
> 
> yes, oppo is made far more accessible. that said the idea that cognazine kills off rot is again immersion breaking. further in order to make a useful amount of oppo to have a reasonable effect on the body you have to rely on so much space carp that you might be able to bring back A patient who is rotting. this allows you to instead dedicate time to the mending or patients and clear out your morgue without having to hope that xenos attack so you can clone, or that salvage remembers to bring you caprs. having played salvage on this server, none of the salvagers understood why i was collecting carp to take to medical, but med thanked me for bringing them carps as apparently there were rotting bodies they needed to take care of.
> 
> finally, this code change I will eventually be sending up to EE in fact i have been asked to do just that before i do, I want to get some play testing done to find a good balance. see what else might need to be tweaked so that when it is given to the up streams it is balanced on all servers using it

Ah, the use of 100lbs of ointments IS really immersion breaking, and the fact that cryo IS slow is a very good point, you can only put it maybe one or two people at a time on a station. Honestly, giving it more thought a few days after I made the post, it may not be as unbalanced as I worried about. And I think the salvagers having to remember to bring carp meat to medical is an interesting link between departments, but also understandable that why that's annoying, and why cognizine really makes no sense to why it's used for oppo from every point besides a gameplay standpoint.

and, agreed, fuck cloning, I hate cloning, and these meds would genuinely help prevent cloning, I was just worried it'd help TOO much, but with how slow cryo still would be, and limited patient use, I think I've changed my mind a bit. Was just worried on first viewing, but thanks for clarifying on my points, helped me rethink my view! I hope I didn't come off too harshly, wasn't meant to be that way!

**Comment by neuPanda** [comment]
> > > As a person that plays medical in chemistry a lot, these changes are VERY overpowered for medical. I do understand that cryopods are severely underused when it comes to medical on Floof, but these would cause death to be trivialized when it comes to revivals.
> > > 
> > > * With one fully potent aloe that gives you 10u of aloe, you can make 20u of Aloxadone to heal 120 of every burn damage, doubled to 240 since you double the chems in the cryopod, imagine how much you can heal with more than a single piece of Aloe.
> > > * One galaxythistle, which could produce 10u of stellibelin (with a max yield of 25u of stellibelin), would heal 240 poison since 10u of stellibelin is needed for making 10u of stelloxadone, which heals 12 poison every unit, and with the cryo's doubling, would mean a single galaxythistle of lower-than-average quality can heal someone fully of poison.
> > > * Since 1u of silver is needed to make 3u of formaldehyde, and 1u of formaldehyde is needed for 3u of oppo, with one bar of silver, you get 10u of silver which turns into 90u of opporozidone. From my knowledge, this would be enough to heal a bloated corpse to fresh, but this amount can heal 2 bloated corpses to max since 90u of oppo becomes 180u with the cryopod change. This is still mildly balanced since 6 sheets of plasma is needed to create the 90u of oppo, but before, cognizine was the primary bottleneck as it required carpotoxin and siderlac, while plasma is usually available.
> > > 
> > > While yes, there are a lot of other chems in the recipe you need to make each of these recipes, they are all chemicals you can make with the resources you get with the chemvend, which can be restocked from Logistics. The primary bottleneck when it comes to chem making is stuff you need outside the chemvend, which is shown above that just a single piece of one of the items required can have a giant impact. The brute cryo chem doesn't even need any outside resources to make it! Primarily, the cryopod doubling chemicals put inside would make it incredibly easy to revive as long as you just have some of the materials above, which could have a negative impact on roleplay since death is a LOT less needed to be worried about.
> > 
> > 
> > as a medic main, this is something i took into consideration. I can make the same argument that topicals trivialize death
> > that said, from an RP stand point, the use of 100lb of ointments mixed with a pile of ash (500 heat damage) stuffed inside of a body woven of Band-Aids (500 brute damage) only to be shocked to be brought back to life in perfect condition infuriates me. that is such an immersion break for me that it become mechanics over roleplay and i hate it
> > things to keep in mind this is not a fast heal, the cryo chamber just reduces resource costs of what is put into it yes, but it only heals a small amount per tick. normal chems are much faster
> > there is only 1 cryo tube if any on most maps. this means that when you have a flood of people you can only take care of one of them at a time via cryo.
> > the primary chems you will use for cryo would all require you to request resources from out side of your department. not that it is hard to ask bottony for aloe and galaxy thistle but when it comes to healing the dead who have died to burn or being spaced. we are looking at extremely high damage levels.. so while yes that 1 aloe was able to heal 240 burn during testing, it took 80 seconds to do it, and i still needed another 2 aloe plants before i could have revived my test dummy.
> > the chems that are used for damage that stops at death, ie tox and genetics. those cryo meds now have negative effects that damage the body
> > finally. fuck cloning. I know a lot of people that their skin crawls when they are forced into a different body type. it might not for everybody, but i have seen others, and even my self seethed with anger because when i was cloned i got a random re-role into a different race.
> > yes, oppo is made far more accessible. that said the idea that cognazine kills off rot is again immersion breaking. further in order to make a useful amount of oppo to have a reasonable effect on the body you have to rely on so much space carp that you might be able to bring back A patient who is rotting. this allows you to instead dedicate time to the mending or patients and clear out your morgue without having to hope that xenos attack so you can clone, or that salvage remembers to bring you caprs. having played salvage on this server, none of the salvagers understood why i was collecting carp to take to medical, but med thanked me for bringing them carps as apparently there were rotting bodies they needed to take care of.
> > finally, this code change I will eventually be sending up to EE in fact i have been asked to do just that before i do, I want to get some play testing done to find a good balance. see what else might need to be tweaked so that when it is given to the up streams it is balanced on all servers using it
> 
> Ah, the use of 100lbs of ointments IS really immersion breaking, and the fact that cryo IS slow is a very good point, you can only put it maybe one or two people at a time on a station. Honestly, giving it more thought a few days after I made the post, it may not be as unbalanced as I worried about. And I think the salvagers having to remember to bring carp meat to medical is an interesting link between departments, but also understandable that why that's annoying, and why cognizine really makes no sense to why it's used for oppo from every point besides a gameplay standpoint.
> 
> and, agreed, fuck cloning, I hate cloning, and these meds would genuinely help prevent cloning, I was just worried it'd help TOO much, but with how slow cryo still would be, and limited patient use, I think I've changed my mind a bit. Was just worried on first viewing, but thanks for clarifying on my points, helped me rethink my view! I hope I didn't come off too harshly, wasn't meant to be that way!

no worries, we all get patinate about our fields
also having somebody look at it with a critics eye is important
the goal is to eventually get a solid game play loop that allows for better med RP
its a lot easier for me to RP somebody in a cryo pod
but wen the medics pull all the beds to the center of the room and 4 docs are trying to speed run healing a patient....
last shift was ruined for me because of that.  i am on an MRP server to RP not to speed run mechanics
I feel you have a similar opinion based on your passion
so if this makes it threw i would love to get more feedback on how it feels and what needs to be tweaked to make it better

**Review by Memeji — APPROVED** [review]

**Pull request merged**
