### PR TITLE
Upstream Merge 2024-10-13

### PR DESCRIPTION
**Pull request by Mnemotechnician**
# Description
Routine upstream merge. Salvage was given a big ass ship, cargo can now buy hardsuits and mine normality crystals (rest in peace code white, never to be remembered), some fixes, two new maps, and more.

# Changelog
:cl:
- add: Upstream merge. See the Einstein-Engines changelog tab for more details

### CODE REVIEW

**Comment by FoxxoTrystan** [comment]
There is no plan atm to do an upstream merge, this will be halted until so.

**Comment by VMSolidus** [comment]
> There is no plan atm to do an upstream merge, this will be halted until so.

Awww, why is that?

**Comment by Mnemotechnician** [comment]
The PR can be updated and merged whenever (but no earlier than issues with it are fixed), so it will be here for the time being.

**Comment by FoxxoTrystan** [comment]
> > There is no plan atm to do an upstream merge, this will be halted until so.
> 
> Awww, why is that?

Waiting for more Upstream PRs to be merged and waiting this to be merged: https://github.com/Simple-Station/Einstein-Engines/pull/1032

**Comment by Mnemotechnician** [comment]
> > > There is no plan atm to do an upstream merge, this will be halted until so.
> > 
> > 
> > Awww, why is that?
> 
> Waiting for more Upstream PRs to be merged and waiting this to be merged: [Simple-Station/Einstein-Engines#1032](https://github.com/Simple-Station/Einstein-Engines/pull/1032)

I can early merge that

**Comment by FoxxoTrystan** [comment]
please do so

**Comment by Mnemotechnician** [comment]
It's done. Do note that even though the checks have passed, we still need someone to actually test the changes (and especially make sure the custom specie name migration works).

**Comment by Mnemotechnician** [comment]
Everything works it seems:

<details>

image

image

image

image

Custom species names:

image

image


</details>

**Comment by Mnemotechnician** [comment]
Now it brings us up to date with the latest stable EE release and includes improved mail, non-edible brains, and more.

**Review by FoxxoTrystan — APPROVED** [review]
Test fails are not valid.

**Comment by Mnemotechnician** [comment]
> Test fails are not valid.

Yea, one of them is gonna be fixed on EE master, the other is python (pip) being shit.

**Comment by Mnemotechnician** [comment]
Okay, how about i just close this and merge latest EE instead, skipping two releases?

**Review by Memeji — CHANGES_REQUESTED** [review]
Look good besides two things:
1: The reverse-engineered Cybersun suits should be removed from being bought by logi.
2: On the map Gaxstation, there's a LV cable missing, which allows easy access to the nuke disk and the Captain's quarters/Bridge.

image_2024-10-19_182723925
image_2024-10-19_182628581

**Comment by FoxxoTrystan** [comment]
> Okay, how about i just close this and merge latest EE instead, skipping two releases?

Review the changes but also lets keep it the most stable version for the moment.
Unless Floof/Memej feels the server is ready for a **VERY BIG UPDATE**

**Comment by VMSolidus** [comment]
> > Okay, how about i just close this and merge latest EE instead, skipping two releases?
> 
> Review the changes but also lets keep it the most stable version for the moment. Unless Floof/Memej feels the server is ready for a **VERY BIG UPDATE**

Master is now less buggy than Stable.

**Comment by VMSolidus** [comment]
> Look good besides two things: 1: The reverse-engineered Cybersun suits should be removed from being bought by logi. 2: On the map Gaxstation, there's a LV cable missing, which allows easy access to the nuke disk and the Captain's quarters/Bridge.
> 
> image_2024-10-19_182723925 image_2024-10-19_182628581

Report this here so it will actually be fixed.
https://github.com/Simple-Station/Einstein-Engines/issues

**Comment by Mnemotechnician** [comment]
> Look good besides two things: 1: The reverse-engineered Cybersun suits should be removed from being bought by logi. 2: On the map Gaxstation, there's a LV cable missing, which allows easy access to the nuke disk and the Captain's quarters/Bridge.

1 was commented out - I don't know why they were even added.
2 needs to be fixed on EE, we can't just safely edit maps without causing massive merge conflicts.

**Review by Memeji — APPROVED** [review]
Works for me, the map issue will have to be fixed upstream

**Review by FoxxoTrystan — CHANGES_REQUESTED** [review]
Test fails are valid.

**Review by Memeji — CHANGES_REQUESTED** [review]
One more change needed, Test fail is valid

**Comment by FoxxoTrystan** [comment]
> > Look good besides two things: 1: The reverse-engineered Cybersun suits should be removed from being bought by logi. 2: On the map Gaxstation, there's a LV cable missing, which allows easy access to the nuke disk and the Captain's quarters/Bridge.
> 
> 1 was commented out - I don't know why they were even added. 2 needs to be fixed on EE, we can't just safely edit maps without causing massive merge conflicts. If it bothers you too much, I will just remove gax from rotation until it's fixed.

Ye remove it from map rotation.

**Comment by VMSolidus** [comment]
> > > Look good besides two things: 1: The reverse-engineered Cybersun suits should be removed from being bought by logi. 2: On the map Gaxstation, there's a LV cable missing, which allows easy access to the nuke disk and the Captain's quarters/Bridge.
> > 
> > 
> > 1 was commented out - I don't know why they were even added. 2 needs to be fixed on EE, we can't just safely edit maps without causing massive merge conflicts. If it bothers you too much, I will just remove gax from rotation until it's fixed.
> 
> Ye remove it from map rotation.

Nah fuck that, I'll fix it myself thank you very much.

**Comment by Mnemotechnician** [comment]
> One more change needed, Test fail is valid

Oops, should be fixed now.

**Comment by Memeji** [comment]
> Done. @Memeji Please make sure to report future issues like this to https://github.com/Simple-Station/Einstein-Engines/issues
> 
> [Simple-Station/Einstein-Engines#1112](https://github.com/Simple-Station/Einstein-Engines/pull/1112)

Will do

**Review by Memeji — APPROVED** [review]

**Comment by FoxxoTrystan** [comment]
This PR will not be merged, after some talk and request.
"Stable" by Solidus talk was deemed too buggy and a bunch of fixes by floof request was done on EE/Master

We will Merge instead the latest "Master" of EE, il making a PR regarding it ASAP.

**Comment by VMSolidus** [comment]
Yea, by Floofmin's reqest, I have done nothing but fix bugs for 3 days. So EE Master has 3 entire pages of merged PRs that all fix issues reported to the issue tracker.

image

**Comment by Mnemotechnician** [comment]
> We will Merge instead the latest "Master" of EE, il making a PR regarding it ASAP.

Do fork from this branch because otherwise you will face more merge conflicts. And as obvious as it may sound, do not remove any content that breaks due to the merge. We've already had enough content lost in previous merges (some of it is still not restored - secwatch is still missing, for example.

**Comment by Mnemotechnician** [comment]
OR I can do the master merge myself right now. Will be easier that way.

**Pull request closed without merging**
