### PR TITLE
Feat: Departament-Specific Lathes

### PR DESCRIPTION
**Pull request by Mnemotechnician**
# Description
This brings back the service, engineering, and cargo techfabs, along with brand new listings and boards for them, and improves the secfab and the medfab.

The heads of the respective departaments get the respective techfab boards in their lockers. Whether they choose to let their whole dept access them, or just themselves, is up to them.

---

The service techfab is mostly used to produce various service tools, such as mops, spray bottles, speed boots, DAW & jukebox boards, station maps, etc

The engi techfab includes all static recipes of the autolathe, AND allows to manufacture most atmospheric machines, most generators, the power monitoring and atmos alert computers, shuttle things, etc. It can also make advanced tools, except for JoL which are too OP.

The cargo techfab includes all static recipes of the autolathe, as well as some cargo tools (mining drill, grapple, handheld mass scanner, tether guns (in case epi researches T3 experimental, cargo can put it to use for once. This is like the only practical use for those other than just goofing around).

The secfab can now make various surveillance boards, speed boots, jaws of life, impassable holobarrier projectors (T2 experimental), and more. I didn't add magboots to the list because there's another PR adding security-specific magboots.

The medfab can now make some stuff that may be useful for paramedics - station maps and the like, as well as the boards for some medical equipment - cloning machines and consoles, stationary crew monitor, etc. The cloning pod is not currently available as a research, so it's never going to actually be producible.

Epistemics still has their protolathe & curcuit imprinter, which are largerly unchanged, with the only exception of adding the atmos alert computer board to the circuit imprinter.

---

This PR also makes the atmospherics alert computer researchable and manufacturable, and adds the new boards to the random machine board pool.

---

The changes were made in the original files with the hope of backporting this to EE later on.

---

<details><summary><h1>Media</h1></summary>
<p>

image

image

image

image

image

image

image

image

</p>
</details>

# Changelog
:cl:
- add: The heads of logistics, service, and engineering can now find brand-new department-specific techfab boards in their lockers.
- add: The list of things the medical and security techfabs can produce has been expanded.

### CODE REVIEW

**Comment by FoxxoTrystan** [comment]
This is going under review in maintainer team but il say my personnal view on this, i dont like having too many lathe, autolathe seem to be the default that simply needed, then circuit printer should be used for all circuit (wait is circuit printer even a thing in the game yet?)

But again this is gona go under a maintainer review.

**Comment by FoxxoTrystan** [comment]
Merge Conflicts but very intrested.

**Comment by Mnemotechnician** [comment]
Ugh, I'm gonna fix them quickly...

**Review by Memeji — APPROVED** [review]
Reviewed with Trystan, no map updates but that'll come later.
Looks great!

**Pull request merged**
