### PR TITLE
Remove Core

### PR DESCRIPTION
**Pull request by flyingkarii**
# Description
This PR exists as Core is not currently suitable and/or able to withstand the initial power requirements that it needs. Given this, and other reasons (playability, overall fun in hectic scenarios, anything except being pretty), I feel Core should be reworked and removed from the pool until further notice.

---

# TODO

---
- [x] Remove Core from pool.

<details><summary><h1>Media</h1></summary>
<p>

Example Media Embed

</p>
</details>

---

# Changelog

:cl: sleepyapril
- remove: Removed Core.

### CODE REVIEW

**Comment by Mnemotechnician** [comment]
Do not remove it from anything other than the map rotation, otherwise it will cause issues later.

**Comment by flyingkarii** [comment]
True true, will do

**Comment by VMSolidus** [comment]
Uhhh. Maybe report in greater detail what issues Core(Supermatter) has? Because I'd be glad to fix whatever issues it's got.

**Comment by VMSolidus** [comment]
This is actually the first I have ever heard of Core having issues.

**Comment by flyingkarii** [comment]
> Uhhh. Maybe report in greater detail what issues Core(Supermatter) has? Because I'd be glad to fix whatever issues it's got.
Comes with one AME core, which doesn't supply power at the start and SMES' run out extremely fast and we go without power for 10-15 minutes no matter what.

**Comment by VMSolidus** [comment]
> > Uhhh. Maybe report in greater detail what issues Core(Supermatter) has? Because I'd be glad to fix whatever issues it's got.
> 
> Comes with one AME core, which doesn't supply power at the start and SMES' run out extremely fast and we go without power for 10-15 minutes no matter what.

Mmm. Alright. Give me a survey on how long it typically takes Floof engineering players to setup Supermatter. And I'll add power generators/and/or SMES extensions to increase the time the station has to stay powered for that amount of time, +10 or so minutes.

**Comment by flyingkarii** [comment]
> > > Uhhh. Maybe report in greater detail what issues Core(Supermatter) has? Because I'd be glad to fix whatever issues it's got.
> > 
> > 
> > Comes with one AME core, which doesn't supply power at the start and SMES' run out extremely fast and we go without power for 10-15 minutes no matter what.
> 
> Mmm. Alright. Give me a survey on how long it typically takes Floof engineering players to setup Supermatter. And I'll add power generators/and/or SMES extensions to increase the time the station has to stay powered for that amount of time, +10 or so minutes.

Usually? Seems like 20 minutes max.

**Comment by VMSolidus** [comment]
> > > > Uhhh. Maybe report in greater detail what issues Core(Supermatter) has? Because I'd be glad to fix whatever issues it's got.
> > > 
> > > 
> > > Comes with one AME core, which doesn't supply power at the start and SMES' run out extremely fast and we go without power for 10-15 minutes no matter what.
> > 
> > 
> > Mmm. Alright. Give me a survey on how long it typically takes Floof engineering players to setup Supermatter. And I'll add power generators/and/or SMES extensions to increase the time the station has to stay powered for that amount of time, +10 or so minutes.
> 
> Usually? Seems like 20 minutes max.

When github stops shitting itself for me, I can touch on that no problem.

**Pull request closed without merging**
