### PR TITLE
Upstream Merge 2024-08-31

### PR DESCRIPTION
**Pull request by Mnemotechnician**
# Description
Catches up with upstream. Taking the liberty to revert #125 and early-merge https://github.com/Simple-Station/Einstein-Engines/pull/812 (4 lines changed, but we really need it here) in the process.

Needs further testing to see if any floof features were broken; quick testing revealed no issues.

<details><summary><h1>Media</h1></summary>
<p>

TODO: media

</p>
</details>

---

# Changelog
:cl:
- add: Upstream merge. See the einstein-engines changelog tab for more details!

### CODE REVIEW

**Comment by Mnemotechnician** [comment]
WHY IS THERE 340 000 LINES ADDED

**Comment by Mnemotechnician** [comment]
As far as I'm concerned everything works, and glacier, core, and saltern are now real. Test fail is fake again.

**Comment by Fansana** [comment]
SM saltern?

**Comment by FoxxoTrystan** [comment]
News map got added in this upstream merge, Those new maps support the SM.

**Comment by FoxxoTrystan** [comment]
I noticed thats not a lot of commits anyway, so should be good.

**Review by FoxxoTrystan — APPROVED** [review]

**Comment by VMSolidus** [comment]
> WHY IS THERE 340 000 LINES ADDED

image

**Comment by ShatteredSwords** [comment]
I heard Train is next. I can't wait to become motion sick!

**Review by Memeji — APPROVED** [review]

**Pull request merged**
