### PR TITLE
Irregular Extended Fix

### PR DESCRIPTION
**Pull request by fenndragon**
# Description

Fixes the Irregular extended event scheduler to properly have the same settings as Irregular, just with a longer shift time. 

---
# Changelog

:cl:

- fix: Fixed Irregular Extended

### CODE REVIEW

**Review by Memeji — CHANGES_REQUESTED** [review]
This would be the same as replacing the "IrregularExtendedStationEventScheduler" game rule with the "IrregularStationEventScheduler" game rule.

Meaning they're duplicates.

**Comment by fenndragon** [comment]
> This would be the same as replacing the "IrregularExtendedStationEventScheduler" game rule with the "IrregularStationEventScheduler" game rule.
> 
> Meaning they're duplicates.

they aren't duplicates because one is extended (is it not?) I thought the point of "irregular extended" was, it has the irregular event scheduler and a longer base shift?

**Comment by Memeji** [comment]
> > This would be the same as replacing the "IrregularExtendedStationEventScheduler" game rule with the "IrregularStationEventScheduler" game rule.
> > Meaning they're duplicates.
> 
> they aren't duplicates because one is extended (is it not?) I thought the point of "irregular extended" was, it has the irregular event scheduler and a longer base shift?

The game rules are the same.

As seen:
- type: entity
  id: IrregularStationEventScheduler
  parent: BaseGameRule
  noSpawn: true
  components:
  - type: OscillatingStationEventScheduler
    minChaos: 0.8
    maxChaos: 14
    startingSlope: 0.2
    downwardsLimit: -0.35
    upwardsLimit: 0.4

- type: entity
  id: IrregularExtendedStationEventScheduler
  parent: BaseGameRule
  noSpawn: true
  components:
  - type: OscillatingStationEventScheduler
    minChaos: 0.8
    maxChaos: 14
    startingSlope: 0.2
    downwardsLimit: -0.35
    upwardsLimit: 0.4

The values are the same, so it would be better to use the "IrregularStationEventScheduler" if anything.
But the point of the Extended version is to have a bias towards less chaos, so that the station lasts longer instead of being more chaotic and ending faster.

**Comment by fenndragon** [comment]
> > > This would be the same as replacing the "IrregularExtendedStationEventScheduler" game rule with the "IrregularStationEventScheduler" game rule.
> > > Meaning they're duplicates.
> > 
> > 
> > they aren't duplicates because one is extended (is it not?) I thought the point of "irregular extended" was, it has the irregular event scheduler and a longer base shift?
> 
> The game rules are the same.
> 
> As seen:
> 
> * type: entity
>   id: IrregularStationEventScheduler
>   parent: BaseGameRule
>   noSpawn: true
>   components:
>   
>   * type: OscillatingStationEventScheduler
>     minChaos: 0.8
>     maxChaos: 14
>     startingSlope: 0.2
>     downwardsLimit: -0.35
>     upwardsLimit: 0.4
> * type: entity
>   id: IrregularExtendedStationEventScheduler
>   parent: BaseGameRule
>   noSpawn: true
>   components:
>   
>   * type: OscillatingStationEventScheduler
>     minChaos: 0.8
>     maxChaos: 14
>     startingSlope: 0.2
>     downwardsLimit: -0.35
>     upwardsLimit: 0.4
> 
> The values are the same, so it would be better to use the "IrregularStationEventScheduler" if anything. But the point of the Extended version is to have a bias towards less chaos, so that the station lasts longer instead of being more chaotic and ending faster.

ok but at present it causes nothing to spawn at all whatsoever, isn't the name irregular extended a bit misleading if it's meant to be less of an extended shift with an irregular event scheduler and moreso a shift without any events?

**Comment by Memeji** [comment]
> > > > This would be the same as replacing the "IrregularExtendedStationEventScheduler" game rule with the "IrregularStationEventScheduler" game rule.
> > > > Meaning they're duplicates.
> > > 
> > > 
> > > they aren't duplicates because one is extended (is it not?) I thought the point of "irregular extended" was, it has the irregular event scheduler and a longer base shift?
> > 
> > 
> > The game rules are the same.
> > As seen:
> > 
> > * type: entity
> >   id: IrregularStationEventScheduler
> >   parent: BaseGameRule
> >   noSpawn: true
> >   components:
> >   
> >   * type: OscillatingStationEventScheduler
> >     minChaos: 0.8
> >     maxChaos: 14
> >     startingSlope: 0.2
> >     downwardsLimit: -0.35
> >     upwardsLimit: 0.4
> > * type: entity
> >   id: IrregularExtendedStationEventScheduler
> >   parent: BaseGameRule
> >   noSpawn: true
> >   components:
> >   
> >   * type: OscillatingStationEventScheduler
> >     minChaos: 0.8
> >     maxChaos: 14
> >     startingSlope: 0.2
> >     downwardsLimit: -0.35
> >     upwardsLimit: 0.4
> > 
> > The values are the same, so it would be better to use the "IrregularStationEventScheduler" if anything. But the point of the Extended version is to have a bias towards less chaos, so that the station lasts longer instead of being more chaotic and ending faster.
> 
> ok but at present it causes nothing to spawn at all whatsoever, isn't the name irregular extended a bit misleading if it's meant to be less of an extended shift with an irregular event scheduler and moreso a shift without any events?

IMO that is more of an issue with the amount of events that don't really exist.
We have several that don't actually notify anything (Survivor spawns, skeleton spawns, etc) until someone takes those roles. With it being extended, no one does until way later on.
I would prefer more events made that are interesting tbh.

**Review by Memeji — CHANGES_REQUESTED** [review]
So after looking into it, I would modify the bias to not be more biased for downwards.

Remove the biases so it acts normal, but keep the other settings for it to be more of a "chill"/Extended shift.

**Review by Fansana — APPROVED** [review]

**Pull request merged**
