### PR TITLE
Upstream Merge 2024-10-04

### PR DESCRIPTION
**Pull request by Mnemotechnician**
# Description
Routine upstream merge. Lots of fixes, some new psionic powers, harpy language, better narcolepsy, ghost respawn system; nothing really fascinating.

# Media
<details>

image

image

</details>

# Changelog
:cl:
- add: Upstream merge. The the Einstein-Engines changelog tab for more details.

### CODE REVIEW

**Comment by Mnemotechnician** [comment]
The RSI diff workflow fails because the backpack migration files contain spaces in their names.

**Comment by FoxxoTrystan** [comment]
> The RSI diff workflow fails because the backpack migration files contain spaces in their names.

by god i wish this will not cause issues.
OH WELL.

Also i wanted to do an upstream merge after some things, but thats is fine i supose.

**Review by FoxxoTrystan — APPROVED** [review]

**Review by Memeji — APPROVED** [review]

**Review by Memeji — CHANGES_REQUESTED** [review]
Can the issues with the diff check be resolved?

**Comment by Mnemotechnician** [comment]
no, just need to move on and not touch those 4 files ever again

**Comment by VMSolidus** [comment]
I have three PRs you should probably include.
https://github.com/Simple-Station/Einstein-Engines/pull/1012
https://github.com/Simple-Station/Einstein-Engines/pull/1013
https://github.com/Simple-Station/Einstein-Engines/pull/1014

These came after testing feedback from Deepstation.

**Review by Memeji — APPROVED** [review]
I would rather not have this error.

Oh well

**Review by Memeji — CHANGES_REQUESTED** [review]
Sorry, never mind.
This will not be merged until all checks pass.

**Comment by Mnemotechnician** [comment]
Mh, then we are waiting on @VMSolidus to fix this upstream

**Comment by Mnemotechnician** [comment]
Okay, I fixed the workflow by renaming the files, it seems.

**Comment by VMSolidus** [comment]
Hold off on merging this for a bit, I'm having some updates on EE merged that came after the feedback from Saturday's playtest, which are pretty important because the original release version of Shadeskip was **HILARIOUSLY** broken(Not in a server crashing way, but in a grief the server and force a shuttle call kinda way). Also nerfs to Lotophagoi Addiction, and some new positive moodlets.

**Comment by FoxxoTrystan** [comment]
Going to work on this also very soonish.

**Review by FoxxoTrystan — APPROVED** [review]

**Comment by VMSolidus** [comment]
Okay, the upstream patches for various powers are now merged. Y'all should be good to grab them now via another Merge.

**Review by Memeji — APPROVED** [review]

**Comment by FoxxoTrystan** [comment]
Upstream stable for my testing, all 2 Approval done.

This PR should only be merged by @Fansana

**Review by Fansana — APPROVED** [review]

**Pull request merged**
