### PR TITLE
Upstream Merge 2024-09-14

### PR DESCRIPTION
**Pull request by Mnemotechnician**
# Description
Routine upstream merge, catches us with upstream as of 2024-09-14. Floof loadouts were updated in accordance with the new changes as a part of this merge. Also early-merging https://github.com/Simple-Station/Einstein-Engines/pull/890 to "hotfix" an issue with quick constructions.

**NOTE:** for an unknown reason, command loadouts are a bit broken upstream and are placed in "uncategorized" instead of the respective command sub-categories. If that gets fixed upstream before this PR is merged, I'll merge the fix as a part of this PR.

<details><summary><h1>Media</h1></summary>
<p>

image

image

image

</p>
</details>

# Changelog
:cl:
- add: Upstream merge. See the Einstein-Engines tab for more details.

### CODE REVIEW

**Review by Memeji — APPROVED** [review]

**Comment by Memeji** [comment]
Will get Trystan's input as this will be large.

**Comment by Mnemotechnician** [comment]
Most of it is the antag refactor

**Comment by Mnemotechnician** [comment]
Everything still works as far as I could test.

**Review by FoxxoTrystan — CHANGES_REQUESTED** [review]
test fails are valid

**Comment by Mnemotechnician** [comment]
There were outdated references to galactic common in floof prototypes; Just had to change them to tau ceti, now they work.

**Review by FoxxoTrystan — APPROVED** [review]

**Pull request merged**
